### ISSUE TITLE
Add new Feature : Dynamic Messages

### ISSUE THREAD

**Issue by prateek2102** [Yash-Ainapure/dypcetclubs.live#1]
Problem - Currently we are having all the messages hard coded throughout the app.
Advancements - We can make a constants.js file and add all the error messages as well as other messages and export them and import them in files and use them dynamically, this way we will not need to change error messgaes everywhere.

Ex- if we need to change the error message - "Email and password are required" to "Please fill both fields" or anything else we will need to change it everywhere in code but if we have a common constant.js file we will change there and it will reflect everywhere in code.
Reference -

![image](https://github.com/user-attachments/assets/f60ddd7a-840d-41cd-8c39-ed4304f30a7c)

**Comment by prateek2102** [comment]
@Yash-Ainapure  I would like to work on this feature, please assign it to me.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure I would like to work on this feature, please assign it to me.

nice idea.you can work on it

**Comment by prateek2102** [comment]
This issue is addressed in PR #2 .

**Comment by prateek2102** [comment]
Hi @Yash-Ainapure , I'm happy to contribute to this project, also i had a query, on hacktoberfest it shows this:
![image](https://github.com/user-attachments/assets/55be13d0-4fab-4aad-b99e-3acfbf05f73a)

Can u please add that label to the PR? or there is something i m missing here?

**Comment by Yash-Ainapure** [comment]
> Hi @Yash-Ainapure , I'm happy to contribute to this project, also i had a query, on hacktoberfest it shows this: ![image](https://private-user-images.githubusercontent.com/130992856/372847909-55be13d0-4fab-4aad-b99e-3acfbf05f73a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzAxNTAsIm5iZiI6MTcyNzg2OTg1MCwicGF0aCI6Ii8xMzA5OTI4NTYvMzcyODQ3OTA5LTU1YmUxM2QwLTRmYWItNGFhZC1iOTllLTNhY2ZiZjA1ZjczYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMTUwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjE3MzQ2MDI4NWNjYjJhNDAzMjdmYzY1ZjQzYWEzODcxNzJhOTQ2OGU0MDBjOWFjNWFiZmJjZTA5Y2MwZjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TgtLrrJqHNcXelUaZ9CSfZ84nvNjk44mIYvdTU_VVc0)
> 
> Can u please add that label to the PR? or there is something i m missing here?

ok I'll see
