### ISSUE TITLE
Add browser logo

### ISSUE THREAD

**Issue by anniepauline** [Yash-Ainapure/dypcetclubs.live#10]
The browser tab doesn't display a logo when it loads in the browser. Update the logo to the one already in the application.

**Comment by mishrayush15** [comment]
Hey mate! I can fix this for you. Could you please assign this task to me, I would love to help you and to contribute to your project.

**Comment by anniepauline** [comment]
there u go!

**Comment by Abhishek332** [comment]
@anniepauline issue is showing unassigned, could I take this up??

**Comment by anniepauline** [comment]
@Abhishek332 are u able to do it?

**Comment by Abhishek332** [comment]
Yes I can
