### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by swarraaa** [Yash-Ainapure/dypcetclubs.live#101]
The text is not visible when typed, since its white colored:
![image](https://github.com/user-attachments/assets/ac6dab33-9ee0-49fa-9819-ea8866ecf470)
![image](https://github.com/user-attachments/assets/01da0b44-abe1-4e2c-8c21-375f08ff436c)

The layout of the footer can be improved as follows:
![image](https://github.com/user-attachments/assets/8224a37c-b3e9-4aa2-a457-912dce1f9f4e)

**Comment by swarraaa** [comment]
@Yash-Ainapure Could you please assign me the issue and add the labels?

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Could you please assign me the issue and add the labels?

Sure,go ahead

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure please asign this issue to me

**Comment by Yash-Ainapure** [comment]
I think its good at present
