### ISSUE TITLE
add 'contact us page"

### ISSUE THREAD

**Issue by Subham1** [Yash-Ainapure/dypcetclubs.live#108]
**Description**:
We need to create a "Contact Us" page that includes a form for users to enter their name, email address, and message. This will help users easily reach out for support, feedback, or inquiries. The page should be linked in the main navigation for easy access.

**Uses**:
Support: Users can ask questions or request assistance.
Feedback: Visitors can provide suggestions or comments.
Inquiries: Potential customers can inquire about products or services

@Yash-Ainapure could you pls assign me this work under gssoc ext label

**Comment by Yash-Ainapure** [comment]
> **Description**: We need to create a "Contact Us" page that includes a form for users to enter their name, email address, and message. This will help users easily reach out for support, feedback, or inquiries. The page should be linked in the main navigation for easy access.
> 
> **Uses**: Support: Users can ask questions or request assistance. Feedback: Visitors can provide suggestions or comments. Inquiries: Potential customers can inquire about products or services
> 
> @Yash-Ainapure could you pls assign me this work under gssoc ext label

At present we don't require that
