### ISSUE TITLE
No content present in events and hiring page

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#110]
Hello
There is no content present in events page and hiring page
Just footer is present
I would like to add it
Pls assign me

![image](https://github.com/user-attachments/assets/b60c1e47-8b4a-4ad4-87d9-f257a11168db)

**Comment by Yash-Ainapure** [comment]
I think its fixed now

**Comment by Gauravtb2253** [comment]
Do you have any specific that I could solve

**Comment by Yash-Ainapure** [comment]
> Do you have any specific issue that I could solve

Some logic things are remaining such as adding members to club and displaying the club (when clicked on view club btn) with their members.
Can you try working on them.

**Comment by Gauravtb2253** [comment]
Yes I can work on displaying the club with their members.
