### ISSUE TITLE
Displaying the club info 

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#111]
Hello
I would like to work on displaying the club with their members.
Pls assign me

**Comment by Yash-Ainapure** [comment]
> Hello I would like to work on displaying the club with their members. Pls assign me

But first we have to create a the add club memebers functionality.
refer the prisma schema,i have made tables in db.

**Comment by Gauravtb2253** [comment]
Actually I am getting some error while adding new club member can you pls guide for this

![image](https://github.com/user-attachments/assets/38f60835-16a1-4511-b022-2af6c7e788ae)

I have compiled the ts code and also included proper routes and functions in the backend

It would be nice if you tell something like what can I do or if you have faced similar kind of error before

Thank you

**Comment by Yash-Ainapure** [comment]
> Actually I am getting some error while adding new club member can you pls guide for this
> 
> ![image](https://private-user-images.githubusercontent.com/114927759/377356938-38f60835-16a1-4511-b022-2af6c7e788ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjQzNzUsIm5iZiI6MTcyOTE2NDA3NSwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc3MzU2OTM4LTM4ZjYwODM1LTE2YTEtNDUxMS1iMDIyLTJhZjZjN2U3ODhhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMTIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWQ4YTAxMjg0NWI5NDMwYTc2NDI1NzRhZTdkNDI4NTQzOGQ5ZjdlNzRiNTBjMWEzM2EyYzEyM2EwNTJiYzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5WduonBaGeiYyI2-pys2dHWtUJF_Pp1HAhiaQTEPNXM)
> 
> I have compiled the ts code and also included proper routes and functions in the backend
> 
> It would be nice if you tell something like what can I do or if you have faced similar kind of error before
> 
> Thank you

Could you try logging the whole error message so that we can find the solution?

**Comment by Yash-Ainapure** [comment]
I think this could be some problems:
1. change the backend url to localhost from file axiosInstance.tsx.
2. the backend cold starts when starting at first for at least 1min so wait for 1min to check again when you request for the first time.
3.I tried to ceate a route to add members which worked for me to add the club member through postman .
here is the code:

```

export const addClubMember = async (req: Request, res: Response) => {
  try {
    const { ClubID } = req.body;
    if (!ClubID) {
      logger.warn("Attempted to add club member with missing required fields.");
      return res
        .status(400)
        .json({ error: "ClubID is required." });
    }

    const newMember = await prisma.clubMember.create({
      data: {
        ClubID,
        FirstName: req.body.FirstName,
        LastName: req.body.LastName,
        Email: req.body.Email,
        Role: req.body.Role,
        JoinDate: req.body.JoinDate,
        ProfileImageURL: req.body.ProfileImageURL,
      },
    });

    logger.info(`New member added to ClubID: ${ClubID}`);
    res.status(201).json(newMember);
  } catch (error) {
    logger.error(`Error adding club member: ${error}`);
    res
      .status(500)
      .json({ error: "An error occurred while adding club member."+error });
  }
};
```


you can verify this by sending request through:
http://localhost:4000/api/clubs/addMember

demo data:
{
  "ClubID":10,
 "FirstName":"Sami",
 "LastName":"Bhangaonkar",
 "Email":"sami@gmail.com",
 "Role":"developer",
 "JoinDate":"10/10/2024",
 "ProfileImageURL":"https://demo.png"   
}

**Comment by Yash-Ainapure** [comment]
@Gauravtb2253 ,
try these solutions or you can tell me to do the backend stuff for you

**Comment by Gauravtb2253** [comment]
export const addClubMember = async (req: Request, res: Response) => {
  try {
    const {
      ClubID,
      FirstName,
      LastName,
      Email,
      Role,
      JoinDate,
      ProfileImageURL
    } = req.body;
    
    console.log(req.body)
    if (!ClubID || !FirstName || !LastName) {
      logger.warn(
        "Attempted to add a club member with missing required fields."
      );
      return res
        .status(400)
        .json({ error: "ClubID, FirstName, and LastName are required." });
    }

    const newMember = await prisma.clubMember.create({
      data: {
        FirstName,
        LastName,
        Email,
        Role,
        JoinDate,
        ProfileImageURL,
        Club: {
          connect: { ClubID } 
        }
      },
    }); 

    logger.info( 
      `New member added to ClubID ${ClubID}: ${FirstName} ${LastName}`
    );
    res.status(201).json(newMember);
  } catch (error) {
    logger.error(`Error adding club member: ${error}`);
    res.status(500).json({ error: "Error adding club member" });
  }
};

this is my code for adding member

**Comment by Gauravtb2253** [comment]
{
  "ClubID": 1,
  "FirstName": "abc",
  "LastName": "def",
  "Email": "abc@gmail.com",
  "Role": "Member",
  "JoinDate": "2024-10-17",
  "ProfileImageURL": "url"
}


this is demo data

**Comment by Gauravtb2253** [comment]
I am getting internal server error

**Comment by Yash-Ainapure** [comment]
> { "ClubID": 1, "FirstName": "abc", "LastName": "def", "Email": "[abc@gmail.com](mailto:abc@gmail.com)", "Role": "Member", "JoinDate": "2024-10-17", "ProfileImageURL": "url" }
> 
> this is demo data

Sorry but the club for club id 1 there is no club present,
that's why the error was coming i think.

refer the below image for adding member to specific club with there id mentioned.
when we login we get the club id in response for that logged club.use that to add the club member when adding thourgh the webaite.

![Screenshot from 2024-10-17 18-16-56](https://github.com/user-attachments/assets/c9675e63-128d-4711-9c50-6c5b0b529fff)

**Comment by Gauravtb2253** [comment]
Can you give me email and password for any one club pls for login purpose

**Comment by Gauravtb2253** [comment]
![image](https://github.com/user-attachments/assets/1d885703-11b6-4a05-b3e2-264bf0b7b3e7)

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/114927759/377531456-1d885703-11b6-4a05-b3e2-264bf0b7b3e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjAzMDIsIm5iZiI6MTcyOTIyMDAwMiwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc3NTMxNDU2LTFkODg1NzAzLTExYjYtNGEwNS1iM2UyLTI2NGJmMGI3YjNlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk2NDYyMzU2NmU2NzZkNmYyMzcyMjA4OTBkMDExZjEzODYxZjg1ZjkyYmFhMmZlMzFkZDE2YjQ5ZjViNGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.04wxsfqyuQnyglhVsMy5_sOJgAGVN4oipOH7srcpEd8)


On backend file axiosInstance.tsx change the url from onrender backend url to http://localhost:4000
See, on render there isn't a route to add member ,its at your local,when we push these changes the onrender will work to addmember.
just remember to change it back to onrender url when pushing.

**Comment by Gauravtb2253** [comment]
the error is solved
I will try to do the work till tonight

**Comment by Yash-Ainapure** [comment]
> the error is solved I will try to do the work till tonight

ok,great

**Comment by Yash-Ainapure** [comment]
Just pull the latest changes or it could create conflicts further
