### ISSUE TITLE
Enhance UI/UX of Quiz Creation

### ISSUE THREAD

**Issue by Laxmi01345** [Yash-Ainapure/dypcetclubs.live#112]
The current UI/UX of the "Create New Quiz" interface can be improved to provide a more user-friendly and visually appealing experience. Below are the suggested improvements:

Form Design:

1. Improve the layout and alignment of the form fields (Quiz Title, Question, Options, Correct Answer).
2. Improve the design of the "Add Question" and "Create Quiz" buttons for better visibility and engagement. Add hover effects to make these buttons interactive.

Responsiveness:

1. Ensure the entire form is fully responsive across various screen sizes, especially mobile and tablet views.
2. Adapt the layout for smaller screens by possibly stacking form fields or adjusting the font sizes to improve usability.

Color Scheme:

1. Update the colour scheme to use more vibrant and contrasting colours for better readability.
2. Ensure the text fields and buttons have adequate contrast with the background for users with visual impairments.
3. These changes will significantly enhance the user experience and improve the overall visual design of the quiz creation interface.

Assign me this issue under gssoc-ext , hacktoberfest  and level

**Comment by Yash-Ainapure** [comment]
> The current UI/UX of the "Create New Quiz" interface can be improved to provide a more user-friendly and visually appealing experience. Below are the suggested improvements:
> 
> Form Design:
> 
> 1. Improve the layout and alignment of the form fields (Quiz Title, Question, Options, Correct Answer).
> 2. Improve the design of the "Add Question" and "Create Quiz" buttons for better visibility and engagement. Add hover effects to make these buttons interactive.
> 
> Responsiveness:
> 
> 1. Ensure the entire form is fully responsive across various screen sizes, especially mobile and tablet views.
> 2. Adapt the layout for smaller screens by possibly stacking form fields or adjusting the font sizes to improve usability.
> 
> Color Scheme:
> 
> 1. Update the colour scheme to use more vibrant and contrasting colours for better readability.
> 2. Ensure the text fields and buttons have adequate contrast with the background for users with visual impairments.
> 3. These changes will significantly enhance the user experience and improve the overall visual design of the quiz creation interface.
> 
> Assign me this issue under gssoc-ext , hacktoberfest and level

Sure,go ahead
