### ISSUE TITLE
Contact Us page Not working

### ISSUE THREAD

**Issue by Ahsankhalid618** [Yash-Ainapure/dypcetclubs.live#115]
Contact Us page is not working, it's either doesn't exist or not working,
I'll design the whole contact page and add form functionality as well.

![image](https://github.com/user-attachments/assets/978ae7a5-1d82-4604-9b83-0dc0ad665876)

Assign me this issue, also add labels of Hacktoberfest, gssoc-ext, level3

**Comment by Yash-Ainapure** [comment]
> Contact Us page is not working, it's either doesn't exist or not working, I'll design the whole contact page and add form functionality as well.
> 
> ![image](https://private-user-images.githubusercontent.com/83424436/377586979-978ae7a5-1d82-4604-9b83-0dc0ad665876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjAyMTAsIm5iZiI6MTcyOTIxOTkxMCwicGF0aCI6Ii84MzQyNDQzNi8zNzc1ODY5NzktOTc4YWU3YTUtMWQ4Mi00NjA0LTliODMtMGRjMGFkNjY1ODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAyNTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTQwMGFhZjZkNzAwZmFiMzZiNjcxOTdlOGFjZWY2NGQ4ZjEzZjU3NzkwNTVkNGE5NjNmMDQ2Yzk2OGM0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UPE-TCwrpJ2ALFNUcqLbKJEyRiNNe_40lbskCtLq8Cw)
> 
> Assign me this issue, also add labels of Hacktoberfest, gssoc-ext, level3

It doesn't exists.
and Currently we don't require that page.
