### ISSUE TITLE
Bug: Navbar should be hidden on scrolling down

### ISSUE THREAD

**Issue by Athaxv** [Yash-Ainapure/dypcetclubs.live#117]
In the navbar section, on scroll down the navbar is still available it overlaps the text present on the other section

here is a image for the problem
![Screenshot 2024-10-18 114618](https://github.com/user-attachments/assets/abb49359-b809-46cd-9791-5839eb27b279)

I want to solve this problem can you assign it to me under hactoberfest and gssoc-ext

**Comment by Yash-Ainapure** [comment]
> In the navbar section, on scroll down the navbar is still available it overlaps the text present on the other section
> 
> here is a image for the problem ![Screenshot 2024-10-18 114618](https://private-user-images.githubusercontent.com/161715841/377745213-abb49359-b809-46cd-9791-5839eb27b279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDIxNTEsIm5iZiI6MTcyOTI0MTg1MSwicGF0aCI6Ii8xNjE3MTU4NDEvMzc3NzQ1MjEzLWFiYjQ5MzU5LWI4MDktNDZjZC05NzkxLTU4MzllYjI3YjI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwODU3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTgyNDMyM2E1Y2Q2NTEzNzM1NmU3NTA3NDk0ZjYxODBkYjViZmE2NzA0NzQ0ZDFhNzFjMTE4NDRhY2VhYTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t2h2BiiS4zJVtJkPwY5gx45-9EKtU-VznzVTKYj4_I4)
> 
> I want to solve this problem can you assign it to me under hactoberfest and gssoc-ext

The navbar should be visible while scrolling
