### ISSUE TITLE
Bug: Club admin login page gets refreshed when we enter login button

### ISSUE THREAD

**Issue by Yash-Ainapure** [Yash-Ainapure/dypcetclubs.live#12]
To form the Issue: 1.(first create a club admin by registering yourself as admin).  
                                   2.click club login button on home page,
                                   3. enter login credentials.
                                   4. and enter Login button,
                                   : Here the page gets refreshed/rerendered due to some bug and we have to enter the login credentials again.

**Comment by Swetabh333** [comment]
@Yash-Ainapure  I'd like to work on this , can you please assign a level to it as well?

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure I'd like to work on this , can you please assign a level to it as well?

Sure, go ahead
