### ISSUE TITLE
Adding contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Yash-Ainapure/dypcetclubs.live#120]
Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors.

**Comment by Yash-Ainapure** [comment]
> Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors.

we don't need such files at present cos at readme.md the installation steps are present
