### ISSUE TITLE
Adding CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Yash-Ainapure/dypcetclubs.live#121]
Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors.
Missing Code of Conduct:

A code of conduct helps maintain a respectful and welcoming community. Without it, contributors may not know what behavior is expected.

**Comment by Yash-Ainapure** [comment]
> Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors. Missing Code of Conduct:
> 
> A code of conduct helps maintain a respectful and welcoming community. Without it, contributors may not know what behavior is expected.

See, the Readme.md file has the steps to install ,so we don't require that
