### ISSUE TITLE
Navbar Links Not Visible on Scroll Due to White Background

### ISSUE THREAD

**Issue by ShaikHafiza** [Yash-Ainapure/dypcetclubs.live#122]
When the user scrolls down on the page, the navbar links remain white in color, making them invisible against a white background. This impacts user experience, as the links are not visible when the background is white or light-colored.

![image](https://github.com/user-attachments/assets/4f398ea2-e2d4-4cfc-a4ec-7684e56966bd)
 
Please assign me this issue.. I would like to work on this

**Comment by Yash-Ainapure** [comment]
> When the user scrolls down on the page, the navbar links remain white in color, making them invisible against a white background. This impacts user experience, as the links are not visible when the background is white or light-colored.
> 
> ![image](https://private-user-images.githubusercontent.com/138603502/377955351-4f398ea2-e2d4-4cfc-a4ec-7684e56966bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzI2ODYsIm5iZiI6MTcyOTI3MjM4NiwicGF0aCI6Ii8xMzg2MDM1MDIvMzc3OTU1MzUxLTRmMzk4ZWEyLWUyZDQtNGNmYy1hNGVjLTc2ODRlNTY5NjZiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNzI2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWMyYzBiM2MyYzg3OTg1YzIzNjY5NTRhMjMyMmViMzBhZmFmOGM5MTNhNmZiZDFjNGJiYjc5NWI5YjVjOGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sxnOUA3DBSkFyl9SCTO5yZIjP9dIKyoFBKTbAGBc2E)
> 
> Please assign me this issue.. I would like to work on this

I got this issue for a long time but no fix, 
could you tell me how do we fix this?

**Comment by ShaikHafiza** [comment]
Possible Solution:
Add a scroll event listener to detect when the user scrolls, and update the navbar link colors accordingly.
Modify the CSS to ensure the link color contrasts with the background when scrolling.

**Comment by Yash-Ainapure** [comment]
> Possible Solution: Add a scroll event listener to detect when the user scrolls, and update the navbar link colors accordingly. Modify the CSS to ensure the link color contrasts with the background when scrolling.

Yes but adding such scrolling event would get dependent on the pages(which can get changes afterwards).
