### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jainaryan04** [Yash-Ainapure/dypcetclubs.live#124]
Feature: Add dark mode using a user defined hook and custom styling to all the pages. The user will be able to switch between the modes via a toggle switch in the navbar.
@Yash-Ainapure  please add gssoc-ext and hacktoberfest-accepted labels and assign it to me so I can start working on it.

**Comment by Yash-Ainapure** [comment]
> Feature: Add dark mode using a user defined hook and custom styling to all the pages. The user will be able to switch between the modes via a toggle switch in the navbar. @Yash-Ainapure please add gssoc-ext and hacktoberfest-accepted labels and assign it to me so I can start working on it.

Currently,we don't require this modes feature.
