### ISSUE TITLE
Add password show/hide functionality on register page

### ISSUE THREAD

**Issue by sps234** [Yash-Ainapure/dypcetclubs.live#125]
Users often make mistakes when they can't see the password they're entering on the register page, leading to frustration and re-entry.

Describe the solution you'd like:

Add a "Show Password" toggle (eye icon) to the password field on the register page, allowing users to view or hide their password for easier input.

Screenshots:
![Screenshot (355)](https://github.com/user-attachments/assets/cbed8b69-e512-47f1-a168-d9bad4b0fdf1)

"Please assign this issue to me so that I can work on it."

**Comment by Yash-Ainapure** [comment]
thanks for your contributions
