### ISSUE TITLE
[BUG] Navbar Overlapping register from  for small screen

### ISSUE THREAD

**Issue by vivekrawat21** [Yash-Ainapure/dypcetclubs.live#127]
![Screenshot from 2024-10-19 22-14-06](https://github.com/user-attachments/assets/cdd499fc-5f13-4986-810f-ea47afae1de7)

**Comment by vivekrawat21** [comment]
@Yash-Ainapure  please assign me this issue

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure please assign me this issue

Sure,go ahead
