### ISSUE TITLE
Custom Modal repeating again and again 

### ISSUE THREAD

**Issue by dev129** [Yash-Ainapure/dypcetclubs.live#129]
Hi @Yash-Ainapure,

I’ve noticed that the custom modal asking "Are you a DYPCET club leader?" appears not only on the homepage but also on other pages across the site. While it’s fine for it to appear once on the homepage, its repeated appearance on every new page is a bit hectic and can become frustrating for users, which negatively impacts the **user experience (UX)**.

To improve the overall flow and ensure smoother navigation, it would be better to limit the modal to display only once on the homepage, or perhaps set a cookie or local storage flag to prevent it from showing repeatedly.

**Comment by Yash-Ainapure** [comment]
> Hi @Yash-Ainapure,
> 
> I’ve noticed that the custom modal asking "Are you a DYPCET club leader?" appears not only on the homepage but also on other pages across the site. While it’s fine for it to appear once on the homepage, its repeated appearance on every new page is a bit hectic and can become frustrating for users, which negatively impacts the **user experience (UX)**.
> 
> To improve the overall flow and ensure smoother navigation, it would be better to limit the modal to display only once on the homepage, or perhaps set a cookie or local storage flag to prevent it from showing repeatedly.

When we refresh the page,That modal appears on window after 3 sec,but on the redirects of other pages,it doesnt occur
