### ISSUE TITLE
Form validation for Register page

### ISSUE THREAD

**Issue by anniepauline** [Yash-Ainapure/dypcetclubs.live#13]
The current validation is applied to each field individually as the user enters data, causing the fields to lag while typing. Instead, implement a form-wide validation that checks all fields upon form submission, rather than validating each field individually at a time.

**Comment by Abhishek332** [comment]
Hi @anniepauline, Could you please assign this issue to me. I just go through it, actually with validation we should improve the UI of registration form as well. it not looks good with much shadows and without borders in inputs. UI should be somewhat similar to login modal. What you say?


<img width="689" alt="Screenshot 2024-10-06 at 7 15 55 PM" src="https://github.com/user-attachments/assets/42c693cc-d43c-4f71-8ac3-6a2b32faedf2">

**Comment by Yash-Ainapure** [comment]
> Hi @anniepauline, Could you please assign this issue to me. I just go through it, actually with validation we should improve the UI of registration form as well. it not looks good with much shadows and without borders in inputs. UI should be somewhat similar to login modal. What you say?
> 
> <img alt="Screenshot 2024-10-06 at 7 15 55 PM" width="689" src="https://private-user-images.githubusercontent.com/80886271/373951617-42c693cc-d43c-4f71-8ac3-6a2b32faedf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjk2OTMsIm5iZiI6MTcyODI2OTM5MywicGF0aCI6Ii84MDg4NjI3MS8zNzM5NTE2MTctNDJjNjkzY2MtZDQzYy00ZjcxLThhYzMtNmEyYjMyZmFlZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAyNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYzdlYWZiZWEyN2YxZDhkNDQ4MWFkNDU1Zjk4ZmFlOTFiYTFmYjZiMThiYWFhOTg1YWE3MWI1Nzk3NjdkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aXxUaMP4kPvZ6WKGS5KoJZSfhWVaF_gKGb-033rEKcI">

The UI is updated with a new pr now.

**Comment by Sourabh782** [comment]
@Yash-Ainapure is this issue available? if yes i m intrested working on it

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure is this issue available? if yes i m intrested working on it

no
