### ISSUE TITLE
Redesign Footer Section

### ISSUE THREAD

**Issue by dev129** [Yash-Ainapure/dypcetclubs.live#130]
Hi @Yash-Ainapure,

I’ve noticed that the footer section on your site appears misaligned and is taking up too much space. I can fix this and enhance its overall look. Once you assign me the issue, I’ll provide the new design within 24 hours of approval.

Let me know if you’d like me to proceed!

**Comment by Yash-Ainapure** [comment]
> Hi @Yash-Ainapure,
> 
> I’ve noticed that the footer section on your site appears misaligned and is taking up too much space. I can fix this and enhance its overall look. Once you assign me the issue, I’ll provide the new design within 24 hours of approval.
> 
> Let me know if you’d like me to proceed!

Its good at present
