### ISSUE TITLE
[Feat]: Adding Chatbot to this website , 

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yash-Ainapure/dypcetclubs.live#133]
Description: We aim to enhance user engagement and support on our website by integrating a chatbot. The chatbot will assist users in finding information, answering common questions, and providing a more interactive experience.

@sanjay-kv Add Gssoc and Hacktoberfest tag and assign this to me.

**Comment by Yash-Ainapure** [comment]
> Description: We aim to enhance user engagement and support on our website by integrating a chatbot. The chatbot will assist users in finding information, answering common questions, and providing a more interactive experience.
> 
> @sanjay-kv Add Gssoc and Hacktoberfest tag and assign this to me.

Its not required at present

**Comment by Jashwanth-rit** [comment]
@Yash-Ainapure sir please , in projects i create issue , but everyone rejects it , how can i contribute if everyone regects, feeling demotivated ,

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure sir please , in projects i create issue , but everyone rejects it , how can i contribute if everyone regects, feeling demotivated ,

Keep focused on one repo and find the issue which are actually required rather than unnecessary one,
for that you will definitely get higher level points

**Comment by Jashwanth-rit** [comment]
ok sir thank you,
