### ISSUE TITLE
[Enhance] updating Footer with subscribe section , 

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yash-Ainapure/dypcetclubs.live#135]
Description: To improve user engagement and build our mailing list, we need to enhance the footer of our website by adding a subscription section. This section will allow users to easily subscribe to our newsletter for updates, news, and promotions.

**Comment by Yash-Ainapure** [comment]
> Description: To improve user engagement and build our mailing list, we need to enhance the footer of our website by adding a subscription section. This section will allow users to easily subscribe to our newsletter for updates, news, and promotions.

Not required at present
