### ISSUE TITLE
[Enhance]: Creating registration form so that user register so that user register to compitaion .

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yash-Ainapure/dypcetclubs.live#136]
Description: To facilitate user participation in our upcoming competition, we need to enhance the application by creating a user registration form. This form will allow users to register for the competition and provide essential information for participation.

**Comment by Yash-Ainapure** [comment]
The reqistrations need some database tables to be implemented firstly so we cannot proceed with it right now

**Comment by Jashwanth-rit** [comment]
@Yash-Ainapure No problem sir , i will improve only frontend.

**Comment by Jashwanth-rit** [comment]
@Yash-Ainapure sir please , in projects i create issue , but everyone rejects it , how can i contribute if everyone regects, feeling demotivated ,
