### ISSUE TITLE
adding icons

### ISSUE THREAD

**Issue by abhi200446** [Yash-Ainapure/dypcetclubs.live#138]
![image](https://github.com/user-attachments/assets/0e2b8ea1-03c0-4a31-b1f7-7e63021bcced)
i want to add some more social media icons here please assign @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/147187417/378539005-0e2b8ea1-03c0-4a31-b1f7-7e63021bcced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzQ0NTgsIm5iZiI6MTcyOTUzNDE1OCwicGF0aCI6Ii8xNDcxODc0MTcvMzc4NTM5MDA1LTBlMmI4ZWExLTAzYzAtNGEzMS1iMWY3LTdlNjMwMjFiY2NlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxODA5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWRiMzE2NTc4MGZjMDhjNDIzNzNhN2VjMWQxNDI2ZmJkOGMzM2FmNDQ5NjA3MjEwNTY0ZjhlY2Y1NTBjY2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0KaghNRShtZnnumVPH6G4bD6JVqaCESH1QB8tP7VlSo) i want to add some more social media icons here please assign @Yash-Ainapure

At present,its enough
