### ISSUE TITLE
Working on the CRUD operations of hiring positions

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#144]
Hello
I would like to work on the operations related to the hiring positions in the admin side

**Comment by Gauravtb2253** [comment]
Can you tell what exactly needed

**Comment by Yash-Ainapure** [comment]
> Can you tell what exactly needed

After clicking on a particular session created ,redirect to a page to display its info.
add a option to create positions for that session and display them there,

then we will display such hiring things on hiring tab of home page and applying logic through there.
this applied persons info will also get displayed on that page of session information

**Comment by Yash-Ainapure** [comment]
@Gauravtb2253 ,
i am making some changes in that page.
i will push it then work on this issue

**Comment by Gauravtb2253** [comment]
Okay

**Comment by Yash-Ainapure** [comment]
> Okay

I have pushed it.
now you can work

**Comment by Gauravtb2253** [comment]
Can you tell what positions to include in a session

**Comment by Yash-Ainapure** [comment]
> Can you tell what positions to include in a session

The admin user will add the positions.
we just have to make it dynamic.

see as a hiring section thing,where positions can be Media team,tech team,etc
