### ISSUE TITLE
Implement Quiz Display and Answer Validation After Quiz Creation

### ISSUE THREAD

**Issue by Laxmi01345** [Yash-Ainapure/dypcetclubs.live#146]
Currently, after a user clicks the "Create Quiz" button, there is no functionality to display the quiz questions or validate user-selected answers. This issue aims to implement a new page that displays the quiz questions and allows users to select answers, with functionality to check and provide feedback on whether the answers are correct.

Task:
Implement the functionality to display quiz questions with multiple choice options after the quiz is created. Users should be able to:

1. View the questions and the available options.
2. Select an answer for each question.
3. Receive feedback on whether the selected answer is correct.

Requirements:

1. Display Quiz Questions:
2. Display each question along with its corresponding options.
3. Provide radio buttons or checkboxes for users to select one or more options (depending on the question type).
4. Answer Selection and Validation:
5. Allow users to select an answer for each question.
6. Validate the selected answer against the correct answer stored in the quiz data.
7. Provide immediate feedback, indicating whether the answer is correct or incorrect.

Feedback:

- Display a message for each question once the user selects an answer:
- "Correct" if the answer matches the stored correct answer.
- "Incorrect" if the answer does not match.

Assign it to me under GSSoC-ext, hacktoberfest

**Comment by Laxmi01345** [comment]
yes I will do it

**Comment by Laxmi01345** [comment]
It looks like the issue has been resolved, as the quiz page is now accessible.

![image](https://github.com/user-attachments/assets/59497da5-5bba-4d3c-902d-c33ca1e0b284)
![image](https://github.com/user-attachments/assets/ce130251-8f63-4212-b3c6-3edc496b3943)
![image](https://github.com/user-attachments/assets/5c5532e3-6fc7-47a1-bfff-22ef65f507a3)

**Comment by Yash-Ainapure** [comment]
> It looks like the issue has been resolved, as the quiz page is now accessible.
> 
> ![image](https://private-user-images.githubusercontent.com/122423386/380423434-59497da5-5bba-4d3c-902d-c33ca1e0b284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDc1MDIsIm5iZiI6MTcyOTk0NzIwMiwicGF0aCI6Ii8xMjI0MjMzODYvMzgwNDIzNDM0LTU5NDk3ZGE1LTViYmEtNGQzYy05MDJkLWMzM2NhMWUwYjI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Nzk1YWM1NmNkMjA4YTJiN2M5YmQzN2UxMzM2NjA2MDNlYmU4YWUxZDY3NDA0MzM3NTE0YWNmMDIzNzJkMjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.inRf-7Zt4u29bdvAEg3kPHQUPdgG3WBObd0CclKvBVc) ![image](https://private-user-images.githubusercontent.com/122423386/380423452-ce130251-8f63-4212-b3c6-3edc496b3943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDc1MDIsIm5iZiI6MTcyOTk0NzIwMiwicGF0aCI6Ii8xMjI0MjMzODYvMzgwNDIzNDUyLWNlMTMwMjUxLThmNjMtNDIxMi1iM2M2LTNlZGM0OTZiMzk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWY3Zjg2MjFlNzkyOWVhOGVmZTU1N2JkYmJmNGIyYmE0OWVmYjQzMzM2OGY2YWE4ZjhmYTkwODBhMmYwNGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JjA_In0moP-ucNR18vcT6yIZNDwuFbpTVLgNxMC_stg) ![image](https://private-user-images.githubusercontent.com/122423386/380423473-5c5532e3-6fc7-47a1-bfff-22ef65f507a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDc1MDIsIm5iZiI6MTcyOTk0NzIwMiwicGF0aCI6Ii8xMjI0MjMzODYvMzgwNDIzNDczLTVjNTUzMmUzLTZmYzctNDdhMS1iZmZmLTIyZWY2NWY1MDdhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWRkMzY5MjY2ZWVmODgzMTVhMjEyZGU0NjEwM2Y3ZDFhMzY3MTFhYWVmNWY5YWFmZDljYmE1NDUxNjk4OWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._GY307wW6UUI0G7qZ8DINm21m4LC1YAaqIa9qRN9M3A)

,Ohh wow,
didn't know how to started working,sorry for that.
I have one more suggestion.
can you implement some restriction things in quiz page?
for example:
1.block user to copy the text
2.warn user if he tries to switch tabs.
some things like that?

**Comment by Laxmi01345** [comment]
sure I will do it
