### ISSUE TITLE
Enhance UI of Quiz Result Page

### ISSUE THREAD

**Issue by Laxmi01345** [Yash-Ainapure/dypcetclubs.live#147]
The current Quiz Result page has a basic user interface. This issue aims to improve the UI for better user experience, visual appeal, and functionality. The goal is to make the result page more engaging and clear for users viewing quiz results.

Task:
Revamp the UI of the Quiz Result page to include:

- A cleaner layout with enhanced design elements for readability and user interaction.
- Improved table styling for quiz results, ensuring each entry is clear and distinguishable.
- A better arrangement for input fields (Quiz ID) and action buttons (Fetch Results).
- More intuitive design elements, such as icons, colors, and spacing to make the page visually appealing.

**Comment by Yash-Ainapure** [comment]
The present UI is good.
I have a issue for you,that
can you add some sortings options for quiz results table?
(such as sort by time,sort by result,etc)

**Comment by Laxmi01345** [comment]
yes sure I will add sorting options
