### ISSUE TITLE
[Documentation] : Wanted To Add Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Yash-Ainapure/dypcetclubs.live#148]
I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

**Comment by Yash-Ainapure** [comment]
> I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.
> 
> Wanted to do the following changes :-
> 
> 1. Enhance the project structure
> 2. Add need help with the basics section
> 3. Add project structure section
> 4. Add additional method of contributing through GitHub desktop section
> 5. Add good coding practices section
> 6. Add the help and support section
> 7. Add the pull request section
> 8. Add issue report process section

Presently,not required
