### ISSUE TITLE
Add FAQ's section

### ISSUE THREAD

**Issue by sriharsha0x1** [Yash-Ainapure/dypcetclubs.live#149]
example
How can I register for an event?
Are the clubs active?
How can I join a club?
many more etc..,

![image](https://github.com/user-attachments/assets/08e54188-807e-41f3-8342-44b6025a74b0)

@Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
> example How can I register for an event? Are the clubs active? How can I join a club? many more etc..,
> 
> ![image](https://private-user-images.githubusercontent.com/165547764/379794792-08e54188-807e-41f3-8342-44b6025a74b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODE1NTEsIm5iZiI6MTcyOTc4MTI1MSwicGF0aCI6Ii8xNjU1NDc3NjQvMzc5Nzk0NzkyLTA4ZTU0MTg4LTgwN2UtNDFmMy04MzQyLTQ0YjYwMjVhNzRiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNDQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDE0MWFjMjQyMzQ3YmMxMzc1NzU0NDA4M2M5NGI4Yjk0OWQ1NTIyYmNiY2JhNWRmM2FmZmM1NWRkODdiZDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SfB4hGThHy6dSQMkLQTD1GCW_gK36xom6oyxOJuNG44)
> 
> @Yash-Ainapure

The faq's are just temporarily added,not required to add more.
