### ISSUE TITLE
[Feat]: adding login with google , and other as well.

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yash-Ainapure/dypcetclubs.live#152]
Description: As part of enhancing the user authentication experience, we need to implement login functionality using Google and other OAuth providers (e.g., Facebook, Twitter). This will allow users to log in more easily and securely, reducing the friction of creating new accounts and remembering passwords.

@sanjay-kv add gssoc and hacktoberfest and assign to me

**Comment by Yash-Ainapure** [comment]
> Description: As part of enhancing the user authentication experience, we need to implement login functionality using Google and other OAuth providers (e.g., Facebook, Twitter). This will allow users to log in more easily and securely, reducing the friction of creating new accounts and remembering passwords.
> 
> @sanjay-kv add gssoc and hacktoberfest and assign to me

Sorry,but currently we don't require this
