### ISSUE TITLE
[Feat]: adding gssoc, hacktoberfest banner and contactus section for readme file.

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yash-Ainapure/dypcetclubs.live#153]
Description: To improve the visibility and engagement of our project, we need to add banners for the GirlScript Summer of Code (GSSoC) and Hacktoberfest, along with a "Contact Us" section in the README file. This will help attract potential contributors and provide clear communication channels for users and collaborators.

@sanjay-kv

**Comment by Yash-Ainapure** [comment]
> Description: To improve the visibility and engagement of our project, we need to add banners for the GirlScript Summer of Code (GSSoC) and Hacktoberfest, along with a "Contact Us" section in the README file. This will help attract potential contributors and provide clear communication channels for users and collaborators.
> 
> @sanjay-kv

not required
