### ISSUE TITLE
Add update and delete functionality for hiring position

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#155]
Hello
I would like to work on the functionality to update and delete hiring position

**Comment by Gauravtb2253** [comment]
should i add the buttons in the hiring page of club admin where the list is displayed

**Comment by Gauravtb2253** [comment]
I mean in the clubAdmin/hiring route where we add the position

So there we also display all the current positions So should I add two buttons for every position as delete or update position

**Comment by Yash-Ainapure** [comment]
> I mean in the clubAdmin/hiring route where we add the position
> 
> So there we also display all the current positions So should I add two buttons for every position as delete or update position

Yes but add the icons on buttons instead of text for update and delete

**Comment by Gauravtb2253** [comment]
I have done the function for updating or deleting 
It works when tried using postman 
But when I try it using the website it gives unauthorized error

**Comment by Gauravtb2253** [comment]
Can you tell me like what could be the issue in the frontend part

**Comment by Yash-Ainapure** [comment]
> I have done the function for updating and deleting It works when tried using postman But when I try it using the website it gives unauthorized error

Check that you have changed the url in axioInstance.tsx file to localhost:4000

**Comment by Gauravtb2253** [comment]
It is on localhost

**Comment by Gauravtb2253** [comment]
![image](https://github.com/user-attachments/assets/fc06e340-42c7-4763-a8da-56c58499033f)

**Comment by Gauravtb2253** [comment]
The token is printed correctly still issue is there

**Comment by Gauravtb2253** [comment]
The issue is solved

**Comment by Yash-Ainapure** [comment]
What was the problem?

**Comment by Gauravtb2253** [comment]
Actually the auth_token was not getting set due to some reasons
So in auth middleware, I added to check the Authorization header also
So it can check token in either cookie or headers

**Comment by Gauravtb2253** [comment]
Do you have more issues

**Comment by Gauravtb2253** [comment]
any updates

**Comment by Yash-Ainapure** [comment]
sorry for late,no,I'll check after some time.

**Comment by Gauravtb2253** [comment]
any updates?

**Comment by Yash-Ainapure** [comment]
> any updates?

For hiring.
now we have to add apply button through which user can apply to that specific position by uploading his/her resume and other details(present in prisma.schema file for applicant).
and this applicants we have to display on admin side (create a decent ui for this like a pop up modal to display the applicants for that specific position after clicking a button view applicants).also display a count of applicans for specific position on admin side to make admin easily view them.

**Comment by Gauravtb2253** [comment]
I would like to work

**Comment by Yash-Ainapure** [comment]
> I would like to work

OK
