### ISSUE TITLE
[FEAT] : Add Contact Us Page

### ISSUE THREAD

**Issue by PriyanshuValiya** [Yash-Ainapure/dypcetclubs.live#158]
**Description**
From this page, user can mail their issue, reviews, and queries directly from the website. 

**Previous Work**
![Screenshot 2024-10-22 210539](https://github.com/user-attachments/assets/76a1b722-32d2-46ea-bc82-9dc168afc7d7)

**Comment by Yash-Ainapure** [comment]
> **Description** From this page, user can mail their issue, reviews, and queries directly from the website.
> 
> **Previous Work** ![Screenshot 2024-10-22 210539](https://private-user-images.githubusercontent.com/147643182/380475481-76a1b722-32d2-46ea-bc82-9dc168afc7d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzQ5OTMsIm5iZiI6MTczMDAzNDY5MywicGF0aCI6Ii8xNDc2NDMxODIvMzgwNDc1NDgxLTc2YTFiNzIyLTMyZDItNDZlYS1iYzgyLTlkYzE2OGFmYzdkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMzExMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzU2YjRjNjNhODg2MWY4NmNkZDc5YjAyN2U4OWRiMWVmY2E2ZTQ4OGUxZDBjNGUxOTJjZjZlMjQyNzUzOGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X2zK4BVPZcIs56MdsuJF3NAC99udsrmY8aJfbWaioNI)

Currently we don't require it
