### ISSUE TITLE
Adding password show/hide functionality

### ISSUE THREAD

**Issue by Sourabh782** [Yash-Ainapure/dypcetclubs.live#16]
![Screenshot 2024-10-05 184902](https://github.com/user-attachments/assets/b5a11fe3-00e4-438e-a2bb-d23d737579e9)

I wanted to add password hide/show button

**Comment by Sarveshk76** [comment]
Hi @anniepauline, @Sourabh782. I would like to work on this issue

**Comment by Sourabh782** [comment]
@anniepauline assign it to me I was the one creating issue, according to rules the one creating issue is to be assigned it

**Comment by Yash-Ainapure** [comment]
> ![Screenshot 2024-10-05 184902](https://private-user-images.githubusercontent.com/103349890/373874302-b5a11fe3-00e4-438e-a2bb-d23d737579e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODY5OTEsIm5iZiI6MTcyODE4NjY5MSwicGF0aCI6Ii8xMDMzNDk4OTAvMzczODc0MzAyLWI1YTExZmUzLTAwZTQtNDM4ZS1hMmJiLWQyM2Q3Mzc1NzllOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwMzUxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yzc4OTc2ZTZmNzcyY2Y5NWZjOThlOWY4MzU0OGJkY2QyY2Y0NDQyYjMzNjU1NTY0ZjNiMmI2MTJlNjg3NjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zHSc7h-AuwbV3QK0-JLtu4TK8lHDdve4S8ve3QIZRIk)
> 
> I wanted to add password hide/show button

Sure,
thanks for creating a issue,
you can work now
