### ISSUE TITLE
ADDING A SCROLL TO TOP BOTTOM ON All THE PAGES

### ISSUE THREAD

**Issue by amiya-cyber** [Yash-Ainapure/dypcetclubs.live#160]
Adding a "Scroll to Top" or "Bottom" feature enhances user experience by making navigation easier on long pages. It improves accessibility, especially for users with disabilities, and offers convenience on mobile devices. This feature allows for quick navigation, keeps users engaged, and is useful for single-page applications with dynamic content. Overall, it boosts website usability and makes content more accessible.

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @Yash-Ainapure  !

**Comment by Yash-Ainapure** [comment]
> Adding a "Scroll to Top" or "Bottom" feature enhances user experience by making navigation easier on long pages. It improves accessibility, especially for users with disabilities, and offers convenience on mobile devices. This feature allows for quick navigation, keeps users engaged, and is useful for single-page applications with dynamic content. Overall, it boosts website usability and makes content more accessible.
> 
> ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3 ASSIGN ME THE WORK THANK YOU @Yash-Ainapure !

Sorry,it is not required at present
