### ISSUE TITLE
[FEATURE] Auto-Swap Carousel for Club Cards and Upcoming Events

### ISSUE THREAD

**Issue by skanarul8002** [Yash-Ainapure/dypcetclubs.live#163]
**Is your feature request related to a problem? Please describe.**  
Currently, users may have to manually navigate through cards displaying club information and upcoming events, which can be inconvenient and disrupt the browsing experience. An automated carousel would allow for a smoother presentation of content without requiring user interaction.

**Describe the solution you'd like**  
An auto-swapping carousel that cycles through club cards and upcoming event cards. The carousel should have adjustable speed and pause on hover, allowing users to focus on specific details if needed. This feature would enhance the user experience by providing a dynamic, continuous display of important information.

**Screenshots**  

![image](https://github.com/user-attachments/assets/445b2fd3-ec45-4df6-a75d-ed09ab982a37)
![image](https://github.com/user-attachments/assets/b05afcf3-efb3-41f1-ac0c-8df010e166cc)

**Check List**  
- [x] I am contributing under GSSoC-ext  
- [x] I am contributing under hacktoberfest  
- [x] I follow contribution guidelines

**Comment by Yash-Ainapure** [comment]
> **Is your feature request related to a problem? Please describe.** Currently, users may have to manually navigate through cards displaying club information and upcoming events, which can be inconvenient and disrupt the browsing experience. An automated carousel would allow for a smoother presentation of content without requiring user interaction.
> 
> **Describe the solution you'd like** An auto-swapping carousel that cycles through club cards and upcoming event cards. The carousel should have adjustable speed and pause on hover, allowing users to focus on specific details if needed. This feature would enhance the user experience by providing a dynamic, continuous display of important information.
> 
> **Screenshots**
> 
> ![image](https://private-user-images.githubusercontent.com/112712827/382062614-445b2fd3-ec45-4df6-a75d-ed09ab982a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjU1MjgsIm5iZiI6MTczMDUyNTIyOCwicGF0aCI6Ii8xMTI3MTI4MjcvMzgyMDYyNjE0LTQ0NWIyZmQzLWVjNDUtNGRmNi1hNzVkLWVkMDlhYjk4MmEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNTI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmFkNjNjMDkyMTM1MWFhZTE3NWZmYzdkN2NmNjg2ZjdjZWU0M2VhZTIxOTRiM2M2ZWVjNGQ3M2Y0OGJhMjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x064l-tlE8Bw-0uIUMvns0ywmTWSw6apH5_yPbTUsOs) ![image](https://private-user-images.githubusercontent.com/112712827/382062697-b05afcf3-efb3-41f1-ac0c-8df010e166cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjU1MjgsIm5iZiI6MTczMDUyNTIyOCwicGF0aCI6Ii8xMTI3MTI4MjcvMzgyMDYyNjk3LWIwNWFmY2YzLWVmYjMtNDFmMS1hYzBjLThkZjAxMGUxNjZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNTI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZThiZjViNDA0ZjllMDc3MTJlMWMzMmY2MzcxNGI2YjY3NmQ2N2NlM2RhMGM3ODc3MWIzMGMwOWMyOGNmNzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2Nh22mYVSB4Zvz3pdMLWhfiW13c88f3_fZm1_1eP7cA)
> 
> **Check List**
> 
> * [x]  I am contributing under GSSoC-ext
> * [x]  I am contributing under hacktoberfest
> * [x]  I follow contribution guidelines

great but i have a doubt that:
In this carousal will the user be able to scroll back to previous event by hand??

**Comment by skanarul8002** [comment]
@Yash-Ainapure, based on your requirements, it is possible to enable both manual scrolling to previous events and automatic scrolling with a fixed time interval. If you prefer manual left-right navigation, that is also achievable. Please let me know your exact requirements, and once assigned, I'll start working on it.

**Comment by Yash-Ainapure** [comment]
sorry to say but i think he current UI is good for the website and we shouldn't change it.
you could contribute to other issues.
thanks

**Comment by skanarul8002** [comment]
There are missing a file CONTRIBUTE.md , so I can raise a issue #169. Assign me with proper labels.
Also we can add a chatbot that helped new user to understand our project. Really this is helpful to any new users that first time visiting this web site ..i trained the chatbot according to our project. so it really helpful. Issue no. #170
