### ISSUE TITLE
Add CONTRIBUTE.md

### ISSUE THREAD

**Issue by skanarul8002** [Yash-Ainapure/dypcetclubs.live#169]
This issue involves creating a `CONTRIBUTE.md` file to guide new contributors in the project. The file will include information on setting up the project locally, coding standards, creating pull requests, reporting issues, and the review process. This document will help ensure that contributions are consistent with project standards and will make it easier for newcomers to contribute effectively.

**Comment by Yash-Ainapure** [comment]
Really no required at present and the contribution steps are written readme.md file
