### ISSUE TITLE
NavBar Transparent

### ISSUE THREAD

**Issue by Sourabh782** [Yash-Ainapure/dypcetclubs.live#17]
Currently navbar is transparent on scrolling, i wanted to fix that
![Screenshot 2024-10-05 185111](https://github.com/user-attachments/assets/97288431-d27a-4e00-b3a6-c6edc90c325c)

**Comment by anniepauline** [comment]
Sure @Sourabh782 ! It's yours

**Comment by Yash-Ainapure** [comment]
@Sourabh782  The issue is same as #9
