### ISSUE TITLE
Add trained Chatbot in our web site

### ISSUE THREAD

**Issue by skanarul8002** [Yash-Ainapure/dypcetclubs.live#170]
This issue focuses on integrating a trained chatbot to assist new users who are unfamiliar with the application's functionalities. The chatbot will provide guidance on navigating the app, understanding features, and answering frequently asked questions. This addition will improve user experience by offering quick and accessible support within the application.

I trained this chatbot according to our Web site.
Please assign me with proper labels then i will start my work on it.
Thanks @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
Heyy @skanarul8002 ,
Currently we don't require any chatbots here as it will also make the website heavy by adding unnecessary stuff 
and get assigned first before starting to work on it.
thanks
