### ISSUE TITLE
Remove the Bugs & Update UI from the Register Page

### ISSUE THREAD

**Issue by NK-Works** [Yash-Ainapure/dypcetclubs.live#177]
![image](https://github.com/user-attachments/assets/225b152a-1566-4ea1-9d1c-3b2f58785809)
I want to remake the register page as the current page contains many bugs and the UI is not good as well

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/132702983/383538740-225b152a-1566-4ea1-9d1c-3b2f58785809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDU0MzUsIm5iZiI6MTczMDkwNTEzNSwicGF0aCI6Ii8xMzI3MDI5ODMvMzgzNTM4NzQwLTIyNWIxNTJhLTE1NjYtNGVhMS05ZDFjLTNiMmY1ODc4NTgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxNDU4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmZmODAyYjgxMDEzZTNmYTJmMjk5ZDNmNmMzZWNmOTMxM2RiYmI5MGQzMjRmM2YzMjE1NTNmZjNkMTk1ZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P7qmDLtsii_94EaqDkaGaOq0KPzbPnX0P24apmb5Q1s) I want to remake the register page as the current page contains many bugs and the UI is not good as well

Sure.
make it like a popup modal,not like a whole page to register as present one
