### ISSUE TITLE
[FEAT] :  Design Eye-Catching Progress Bar and a Back to top button for UI Aesthetics 

### ISSUE THREAD

**Issue by Edasgh** [Yash-Ainapure/dypcetclubs.live#178]
:red_circle: Add a progress bar and a back to top button in all the pages
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** :
- Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.

- Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.

- Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.

@Yash-Ainapure   Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

**Comment by Yash-Ainapure** [comment]
> 🔴 Add a progress bar and a back to top button in all the pages 🔴 **Enhancement Aim** : 🔴 **Changes** :
> 
> * Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.
> * Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.
> * Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.
> 
> @Yash-Ainapure Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

1.Where you will add the progress bar?
2.and we don't require the back to top button.

**Comment by Edasgh** [comment]
> > 🔴 Add a progress bar and a back to top button in all the pages 🔴 **Enhancement Aim** : 🔴 **Changes** :
> > 
> > * Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.
> > * Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.
> > * Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.
> > 
> > @Yash-Ainapure Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels
> 
> 1.Where you will add the progress bar? 2.and we don't require the back to top button.

On scroll progress bar.
Like this:
![Screenshot 2024-11-06 203803](https://github.com/user-attachments/assets/49fe8b6e-220d-4e79-83e4-6b6c78000134)

**Comment by Yash-Ainapure** [comment]
I think it won't look good as we want the website to be minimilistic .
you could contribute to other issues,thanks
