### ISSUE TITLE
Creating of env.example for  development purpose

### ISSUE THREAD

**Issue by rishyym0927** [Yash-Ainapure/dypcetclubs.live#19]
The current repo does not have any .env.example files, if added it will help contributors to setup their project more easily. Please assign this issue under gssoc-ext level 2

**Comment by Yash-Ainapure** [comment]
> The current repo does not have any .env.example files, if added it will help contributors to setup their project more easily. Please assign this issue under gssoc-ext level 2

Sure, you can go ahead.
about levels: As per the given instructions we can only give this issue as level1 as there is no programming logic here,just adding .env.example the demo credentials
