### ISSUE TITLE
Remove events that are expired/out of date

### ISSUE THREAD

**Issue by anniepauline** [Yash-Ainapure/dypcetclubs.live#20]
In the Upcoming Events section, outdated events are being displayed. Update the backend so that any event with a date earlier than the current date is removed from the database.

**Comment by rishyym0927** [comment]
plese assign me this issue

**Comment by Yash-Ainapure** [comment]
> @anniepauline please assign me this issue , I have experience in nodejs and express backend. Also assign me those issues created by me

Sure,go ahead

**Comment by Yash-Ainapure** [comment]
@rishyym0927 ,
when you will be working on it??

**Comment by NK-Works** [comment]
@Yash-Ainapure If you want I can work on it

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure If you want I can work on it

Sure,go ahead
