### ISSUE TITLE
Feature : Implement a light and dark theme toggle feature.

### ISSUE THREAD

**Issue by anniepauline** [Yash-Ainapure/dypcetclubs.live#22]
The light and dark theme feature must allow users to switch between two different visual styles for the application: a light theme with brighter colors and a dark theme with darker colors. Users must be able to toggle between the two themes, typically through a button or switch.

**Comment by softcreations01** [comment]
I can work on this, by adding the the necessary styling to the css and working on the javascript

**Comment by Sourabh782** [comment]
@anniepauline is this issue free? i am intrested, i have worked on same in other repos as well, so that exp will help
