### ISSUE TITLE
Add navigation to Clubs and Upcoming Events section

### ISSUE THREAD

**Issue by anniepauline** [Yash-Ainapure/dypcetclubs.live#23]
When the **Explore Clubs** button is clicked, redirect the user to the Clubs section.
When the **Upcoming Events** button is clicked, redirect the user to the Upcoming Events section.

**Comment by pranavmugatkar** [comment]
hi @anniepauline , can i take the issue

**Comment by Yash-Ainapure** [comment]
@anniepauline ,
I think this issue is same as #4
