### ISSUE TITLE
Feat: Add Contributors list

### ISSUE THREAD

**Issue by yashksaini-coder** [Yash-Ainapure/dypcetclubs.live#26]
Hi, @Yash-Ainapure I would like to create a contributors list in the footer section of the README documentation. We can add contributors list to highlight them & boost their morale.

- the output is like this 

![image](https://github.com/user-attachments/assets/d756fdb1-dc81-4c66-ba48-fb5fa7c2c0c9)

can you assign me this issue as GSSOC contributor & add **labels** to it.

**Comment by Yash-Ainapure** [comment]
> Hi, @Yash-Ainapure I would like to create a contributors list in the footer section of the README documentation. We can add contributors list to highlight them & boost their morale.
> 
> * the output is like this
> 
> ![image](https://private-user-images.githubusercontent.com/115717039/373898809-d756fdb1-dc81-4c66-ba48-fb5fa7c2c0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQxNTcsIm5iZiI6MTcyODE4Mzg1NywicGF0aCI6Ii8xMTU3MTcwMzkvMzczODk4ODA5LWQ3NTZmZGIxLWRjODEtNGM2Ni1iYTQ4LWZiNWZhN2MyYzBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwMzA0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjA3ZTJjOTNiYzg1NGU5N2IwZWQ5ZDNjY2YxZmJiMzk4NjBkMDQ2OTQzMGVkMzkxYzM5YTE0NTAzMTUwZThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Dw8yOj7FcjqGTrnitZA0gK7AfcV4KmKZ4fR7fhHeAY)
> 
> can you assign me this issue as GSSOC contributor & add **labels** to it.

Sure,go ahead

**Comment by Yash-Ainapure** [comment]
Heyy @yashksaini-coder ,we appreciate your dedication towards this repo, sorry to say but I think shubh from #27  has a better approach to make this work done

**Comment by yashksaini-coder** [comment]
I have the same approach to create an action workflow that will automatically update the contributors list, Its first come first assign basis, so I should get to work on this issue. 

If after making the changes there are some additional requirements you have you can raise a new Issue and assign it @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> I have the same approach to create an action workflow that will automatically update the contributors list, Its first come first assign basis, so I should get to work on this issue.
> 
> If after making the changes there are some additional requirements you have you can raise a new Issue and assign it @shubhagarwal1
> 
> @Yash-Ainapure what do you say ?

i think there are more issue @yashksaini-coder can do any thing else why is he doing the work tha is already assigned to someone

**Comment by Yash-Ainapure** [comment]
> > I have the same approach to create an action workflow that will automatically update the contributors list, Its first come first assign basis, so I should get to work on this issue.
> > If after making the changes there are some additional requirements you have you can raise a new Issue and assign it @shubhagarwal1
> > @Yash-Ainapure what do you say ?
> 
> i think there are more issue @yashksaini-coder can do any thing else why is he doing the work tha is already assigned to someone

Sorry @shubhagarwal1 , as per the instructions of gssoc . first some first basis i am merging @yashksaini-coder  's pr

**Comment by shubhagarwal1** [comment]
> > > I have the same approach to create an action workflow that will automatically update the contributors list, Its first come first assign basis, so I should get to work on this issue.
> > > If after making the changes there are some additional requirements you have you can raise a new Issue and assign it @shubhagarwal1
> > > @Yash-Ainapure what do you say ?
> > 
> > 
> > i think there are more issue @yashksaini-coder can do any thing else why is he doing the work tha is already assigned to someone
> 
> Sorry @shubhagarwal1 , as per the instructions of gssoc . first some first basis i am merging @yashksaini-coder 's pr

no problem can i work on auto label issue which will assign auto labels to new raise issues and pr

**Comment by shubhagarwal1** [comment]
> > > > I have the same approach to create an action workflow that will automatically update the contributors list, Its first come first assign basis, so I should get to work on this issue.
> > > > If after making the changes there are some additional requirements you have you can raise a new Issue and assign it @shubhagarwal1
> > > > @Yash-Ainapure what do you say ?
> > > 
> > > 
> > > i think there are more issue @yashksaini-coder can do any thing else why is he doing the work tha is already assigned to someone
> > 
> > 
> > Sorry @shubhagarwal1 , as per the instructions of gssoc . first some first basis i am merging @yashksaini-coder 's pr
> 
> no problem can i work on auto label issue which will assign auto labels to new raise issues and pr @Yash-Ainapure
