### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [Yash-Ainapure/dypcetclubs.live#27]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @Yash-Ainapure  please assign this task to me with level tag

**Comment by Yash-Ainapure** [comment]
> We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility Hey @Yash-Ainapure please assign this task to me with level tag

Sure, go ahead

**Comment by yashksaini-coder** [comment]
I had the same approach, but no problem

**Comment by shubhagarwal1** [comment]
i am working on the issue right now and have rasied the PR
