### ISSUE TITLE
Redesign Club Registration form.

### ISSUE THREAD

**Issue by ZayedShahcode** [Yash-Ainapure/dypcetclubs.live#30]
![image](https://github.com/user-attachments/assets/6bfbd9e8-b42f-4d13-bb13-5b26ae215ea1)

It lacks theme and all the inputs lack border.
I can even add an auto grow function for description box to change its height dynamically as description may be longer.
Overall the UI looks bad and I want to change it. Please assign this issue to me under gssoc extd and hacktober fest tags

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/115407231/373937756-6bfbd9e8-b42f-4d13-bb13-5b26ae215ea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTQ0NzcsIm5iZiI6MTcyODIxNDE3NywicGF0aCI6Ii8xMTU0MDcyMzEvMzczOTM3NzU2LTZiZmJkOWU4LWI0MmYtNGQxMy1iYjEzLTViMjZhZTIxNWVhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMTI5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDVmYzRhMGQwZjgwNzlmZmJiM2MxNTkwZDMzNzE1ZDdkNTUxMzI2OTQ5OGIyMDA4YWU1NGFkZDdlNjU0MDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BJ1ZG-QiQ9WYafVuml-6y6TRXxdSLA3wSs-l_2KITD8)
> 
> It lacks theme and all the inputs lack border. I can even add an auto grow function for description box to change its height dynamically as description may be longer. Overall the UI looks bad and I want to change it. Please assign this issue to me under gssoc extd and hacktober fest tags

Sure,go ahead

**Comment by Yash-Ainapure** [comment]
Thanks for your contribtion.

**Comment by ZayedShahcode** [comment]
My pleasure.
