### ISSUE TITLE
Adding favicon to website

### ISSUE THREAD

**Issue by hetvipopat** [Yash-Ainapure/dypcetclubs.live#31]
I would like to add favicon as per logo of website, kindly assign me this issue (with appropriate labels)

**Comment by Yash-Ainapure** [comment]
> I would like to add favicon as per logo of website, kindly assign me this issue (with appropriate labels)

Sure go ahead

**Comment by hetvipopat** [comment]
Unable to push to repository
![image](https://github.com/user-attachments/assets/80a28923-8761-4a78-85b7-d311e9b29779)

**Comment by Yash-Ainapure** [comment]
> Unable to push to repository ![image](https://private-user-images.githubusercontent.com/157787846/373947767-80a28923-8761-4a78-85b7-d311e9b29779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjk3NTUsIm5iZiI6MTcyODI2OTQ1NSwicGF0aCI6Ii8xNTc3ODc4NDYvMzczOTQ3NzY3LTgwYTI4OTIzLTg3NjEtNGE3OC04NWI3LWQzMTFlOWIyOTc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzQwNGMzZjg1N2JiNmJkODQwMzEyYjkwNGNiNTZjNzFhMDczM2I3NmE0YmMyYjc3ZTZiODY1NDEwMGFjZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yrDupHXrlIRIp6XFBLDcBSP6M5wPaUdG1suQQfA8Iyc)

Did you forked it and working on your repo correctly?

**Comment by Yash-Ainapure** [comment]
you don't have direct access to the repo so, you should fork it,then make a new branch for the issue and then raise a pull request to this repo.

**Comment by hetvipopat** [comment]
> you don't have direct access to the repo so, you should fork it,then make a new branch for the issue and then raise a pull request to this repo.

Yes... I've forked the repo and made a new branch.

**Comment by Yash-Ainapure** [comment]
> > you don't have direct access to the repo so, you should fork it,then make a new branch for the issue and then raise a pull request to this repo.
> 
> Yes... I've forked the repo and made a new branch.

You are trying to push to my repo.
solution: push to your forked repo.
