### ISSUE TITLE
Automate GitHubTagging and labelling of prs and issues 

### ISSUE THREAD

**Issue by shubhagarwal1** [Yash-Ainapure/dypcetclubs.live#34]
I propose to  introduces a GitHub Actions workflow to automate the creation labels. The workflow is will assign auto label to the new assign issue and pr
Please assign this task to me @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
> I propose to introduces a GitHub Actions workflow to automate the creation labels. The workflow is will assign auto label to the new assign issue and pr Please assign this task to me @Yash-Ainapure

Great ,but just don't assign the level tags ,assign other tags

**Comment by shubhagarwal1** [comment]
sure, can you please assign level2 tag to this task as the logic itself is way for the betterment
