### ISSUE TITLE
Web Page Error

### ISSUE THREAD

**Issue by Picodes10** [Yash-Ainapure/dypcetclubs.live#37]
The web page is not rendering.

![Screenshot 2024-10-06 204311](https://github.com/user-attachments/assets/628ad545-76c9-4b8d-9cc7-f9058dd196d3)

**Comment by Swetabh333** [comment]
@Picodes10 that is the backend deployment link , check the frontend link.

**Comment by Yash-Ainapure** [comment]
As there isn't any issue with the rendering,so we are closing this issue
