### ISSUE TITLE
Adding Smooth Transition On Buttons

### ISSUE THREAD

**Issue by iamsohelx** [Yash-Ainapure/dypcetclubs.live#38]
https://github.com/user-attachments/assets/c195dc9a-1362-4770-b6fd-93dfea09643c

Hey @Yash-Ainapure We can improve user experience by adding smooth transition and animation on every button on your website.
Similar to this or as you wanted.

**Comment by iamsohelx** [comment]
https://github.com/user-attachments/assets/cc9f5b44-07e4-420c-930a-b42e8d341e50
**Similar to this or as you wanted.**

@Yash-Ainapure I can help you to do this, could you please assign this task to me

**Comment by Yash-Ainapure** [comment]
> https://github.com/user-attachments/assets/cc9f5b44-07e4-420c-930a-b42e8d341e50 **Similar to this or as you wanted.**
> 
> @Yash-Ainapure I can help you to do this, could you please assign this task to me

Sorry to say but the current styles/animations are ok and doesn't need to be changed.you could try contributing to other issues.
