### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [Yash-Ainapure/dypcetclubs.live#40]
@Yash-Ainapure 
Issue Description: The website currently lacks interactive design elements that enhance user experience. The website is looking good, adding cursor-animation makes it more beautiful, I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under hacktoberfest-accepted, gssoc-ext, level

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Issue Description: The website currently lacks interactive design elements that enhance user experience. The website is looking good, adding cursor-animation makes it more beautiful, I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.
> 
> I’d like to work on adding this feature. Please assign this issue to me under hacktoberfest-accepted, gssoc-ext, level

Could you show me a demo /video of what do you want to do?

**Comment by AswaniBolisetti** [comment]
https://github.com/user-attachments/assets/011540af-ee50-4bcf-939e-fbb7b0892120

like this,

**Comment by Yash-Ainapure** [comment]
> cursor6.mp4 
> @Yash-Ainapure like this,

Sorry the animations will affect the website performance , we want to create a minimilistic , performance  oriented webapp
