### ISSUE TITLE
Re-designing of club cards 

### ISSUE THREAD

**Issue by saloni911** [Yash-Ainapure/dypcetclubs.live#42]
We propose adopting a card-based design similar to Airbnb's layout to display clubs on our website. This design is visually appealing and user-friendly, allowing for an engaging presentation of clubs while keeping the content organized and easily scannable.
Proposed Functionality:
Each club will be displayed in a card format, with the following key elements:
Club image as the header of the card.
Club name, brief description, and key details (e.g., meeting times or upcomi
<img width="1412" alt="club cards" src="https://github.com/user-attachments/assets/fcd9d7ee-8576-409c-948b-b55dc62165df">
ng events) below the image.
A clear "Join" or "Learn More" button to encourage interaction.
The cards will be responsive and optimized for both desktop and mobile screens, ensuring a seamless user experience across devices.
The layout will be designed to support multiple cards in a grid format, with appropriate spacing and padding to maintain visual clarity.

**Comment by Yash-Ainapure** [comment]
> We propose adopting a card-based design similar to Airbnb's layout to display clubs on our website. This design is visually appealing and user-friendly, allowing for an engaging presentation of clubs while keeping the content organized and easily scannable. Proposed Functionality: Each club will be displayed in a card format, with the following key elements: Club image as the header of the card. Club name, brief description, and key details (e.g., meeting times or upcomi <img alt="club cards" width="1412" src="https://private-user-images.githubusercontent.com/139876585/374258696-fcd9d7ee-8576-409c-948b-b55dc62165df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTc2NTYsIm5iZiI6MTcyODM1NzM1NiwicGF0aCI6Ii8xMzk4NzY1ODUvMzc0MjU4Njk2LWZjZDlkN2VlLTg1NzYtNDA5Yy05NDhiLWI1NWRjNjIxNjVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmNjMWVmOWI3YmNkNzEyOTY5NGJmZDZhYTdkMmJhMDA5M2I2MDdlMDQ5ZjhjZGQ2OTM4NjRhOGMyMmExMDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D_VuK3fKndxZHLgZ_x-Kz-N8Jd3RUBInvjxgmrxrqSA"> ng events) below the image. A clear "Join" or "Learn More" button to encourage interaction. The cards will be responsive and optimized for both desktop and mobile screens, ensuring a seamless user experience across devices. The layout will be designed to support multiple cards in a grid format, with appropriate spacing and padding to maintain visual clarity.


Sorry but the current cards match the minimilistic look and currently the image uploading of clubs aren't working so we'll look it afterwards.
