### ISSUE TITLE
login/signup via google firebase authentication.

### ISSUE THREAD

**Issue by riyaaryan2004** [Yash-Ainapure/dypcetclubs.live#44]
### Description
I want to add google firebase authentication for smooth sign in process without email password
I will google button for "continue with google" and functions.
User can directly sign up via google accounts logged in their browser.

### screenshot
![Screenshot 2024-10-08 001755](https://github.com/user-attachments/assets/7d7bb2d1-7818-4db7-8a79-adec6db06a33)

### Checklist

- [x]  I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com)
- [x]  I'm a GSSoC'24-Extd contributor
- [x]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue (optional)

**Comment by pranavmugatkar** [comment]
Hi @anniepauline , can i take the issue ?
