### ISSUE TITLE
Google Authentication using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [Yash-Ainapure/dypcetclubs.live#45]
I would like to implement Google authentication using Firebase. This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure, which is well-established and trusted.

![image](https://github.com/user-attachments/assets/57b7dfa5-7363-4ee3-b127-b5ff03695f77)

**Comment by samriddhitiwary** [comment]
@Yash-Ainapure could you please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by samriddhitiwary** [comment]
@Yash-Ainapure I have worked in this project which were successfully merged also I assure you that I  will be able to compete it

**Comment by samriddhitiwary** [comment]
@Yash-Ainapure ??

**Comment by Yash-Ainapure** [comment]
> I would like to implement Google authentication using Firebase. This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure, which is well-established and trusted.
> 
> ![image](https://private-user-images.githubusercontent.com/151003533/374310761-57b7dfa5-7363-4ee3-b127-b5ff03695f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODc1NDgsIm5iZiI6MTcyODM4NzI0OCwicGF0aCI6Ii8xNTEwMDM1MzMvMzc0MzEwNzYxLTU3YjdkZmE1LTczNjMtNGVlMy1iMTI3LWI1ZmYwMzY5NWY3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMTM0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE5YTM2NzM2MmM3NzBhZDRhMWY0ZTZjNThiNGM4NjlkOTQ0NjVjY2Q0YzMwYzc5YTA2NzI5N2I3ZjU0OGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GHn7g47gNnaQSY4SesvrQBWIa7WeQiBs0hBCIEewR34)

Sorry but the club admin profiles will be on approve bases (by super admin).
so at present implementing google auth is not suitable.
