### ISSUE TITLE
feature : not a suitable good looking scroll bar of your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Yash-Ainapure/dypcetclubs.live#46]
I want to create a good looking scroll bar that suits on you website.

![scroll bar suitable](https://github.com/user-attachments/assets/16c766f1-807e-45f6-86d6-9f3ff85ce86d)

https://github.com/user-attachments/assets/623e595d-7943-43cd-8285-92c2dbec409e

**Comment by Yash-Ainapure** [comment]
> I want to create a good looking scroll bar that suits on you website.
> 
> ![scroll bar suitable](https://private-user-images.githubusercontent.com/135756009/374314021-16c766f1-807e-45f6-86d6-9f3ff85ce86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTgwMjgsIm5iZiI6MTcyODM1NzcyOCwicGF0aCI6Ii8xMzU3NTYwMDkvMzc0MzE0MDIxLTE2Yzc2NmYxLTgwN2UtNDVmNi04NmQ2LTlmM2ZmODVjZTg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2NlM2VlZTk2YjMwM2ZkY2FmOTk0ZDEwNmNiZTMwYjQzN2QwYTA2ZmNiZTY1MGJkODQ5NTFiZGRhMjY5MWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5AtFyy5ZaJPSKk1l4lWgb3D07kC4s6Ybo-y0hGZFJZU)
> 
>  scroll.mp4

Adding such scrollbar won't look good/minimilistic.
could you just hide the scrollbar ??

**Comment by VinayLodhi1712** [comment]
yeah i can do that well i thnk light color scrollbar will look good but you dont want then i just hide only and plz add level in it
