### ISSUE TITLE
Documentation for the project

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [Yash-Ainapure/dypcetclubs.live#5]
I noticed that this project does not have a README file to help users with documentation.

**Comment by Yash-Ainapure** [comment]
> I noticed that this project does not have a README file to help users with documentation.

Sure ,go on

**Comment by Yash-Ainapure** [comment]
> I noticed that this project does not have a README file to help users with documentation.

Sorry for the miss understandings DarshanKrishna,the Readme file was mistakenly put in the Frontend folder ,will move it out now.
you can work on other issues(or create one)
