### ISSUE TITLE
Add club advisor login/signup

### ISSUE THREAD

**Issue by shwetharavindrabaliga** [Yash-Ainapure/dypcetclubs.live#50]
Since it is for clubs, there will be a club head/ advisor, adding login to the club advisors and giving them certain features like:
1) Option to add a hiring alert to which interested students can register themselves and join.
2) Add events that are upcoming
Please assign this to me. @Yash-Ainapure 
I'd like to work more and enhance a website. I myself being the club advisor of Media and Publications Club at my college, I believe I can add more value to the project.

**Comment by Yash-Ainapure** [comment]
> Since it is for clubs, there will be a club head/ advisor, adding login to the club advisors and giving them certain features like:
> 
> 1. Option to add a hiring alert to which interested students can register themselves and join.
> 2. Add events that are upcoming
>    Please assign this to me. @Yash-Ainapure
>    I'd like to work more and enhance a website. I myself being the club advisor of Media and Publications Club at my college, I believe I can add more value to the project.

At present the hiring component is not done and also the registration things.
So for now we could hold this issue.
you can contribute related to such things first then we could do this

**Comment by shwetharavindrabaliga** [comment]
Can I contribute to adding a hiring page?? @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
> Can I contribute to adding a hiring page?? @Yash-Ainapure

Yeah sure.
I'll explain you the workflow first:
Through club admin there is a hiring button in sidebar which should go on hiring page,and there should be a button to start hiring which has further selection of roles & positions which will get added to db under that club.
and when a user clicks on hiring button on home page,he'll get scrolled down to hiring positions opened currently.

firstly There database table should get created related to this stuffs and after--> backend --->frontend.

I'll create the tables and required stuff then if you could contribute to backend or frontend of hiring pages ,it could be great.
I'll mention you when the tables get created by me

**Comment by shwetharavindrabaliga** [comment]
Yes sure, thankyou!

**Comment by Ameerjafar** [comment]
@Yash-Ainapure did you create the table?

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure did you create the table?

Yess,
do you want to work @shwetharavindrabaliga  @Ameerjafar  on backend and frontend of them??

**Comment by Ameerjafar** [comment]
@Yash-Ainapure yes I can work on this

**Comment by shwetharavindrabaliga** [comment]
@Yash-Ainapure  frontend

**Comment by Ameerjafar** [comment]
@Yash-Ainapure let me do the backend

**Comment by Yash-Ainapure** [comment]
Great, please a create new issue so that i could assign you the work
