### ISSUE TITLE
Display less no. of clubs & events on home page

### ISSUE THREAD

**Issue by Yash-Ainapure** [Yash-Ainapure/dypcetclubs.live#53]
![Screenshot_2024-10-09_08_28_13](https://github.com/user-attachments/assets/5f0bb34a-4d25-45fe-8b2d-5e8a837a214e)

Currently the home page displays all the events & clubs present ,
I just want to show 6 clubs & events on home page(also while displaying 6 check if there are 6 present if less than 6 ,display all).

**Comment by Gauravtb2253** [comment]
I can work on this 
pls assign me

**Comment by Yash-Ainapure** [comment]
> I can work on this pls assign me

Sure

**Comment by vikas83pal** [comment]
@Yash-Ainapure please assign me this issue i would like to work on it
