### ISSUE TITLE
Club Details

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [Yash-Ainapure/dypcetclubs.live#56]
I need to create dynamic routing with parallel routing for the best user experience, and to display information about events scheduled for upcoming dates.

**Comment by Yash-Ainapure** [comment]
> I need to create dynamic routing with parallel routing for the best user experience, and to display information about events scheduled for upcoming dates.

Can you explain in detail,what are you going to do?

**Comment by Kuldeepsinghrajpoot** [comment]
![image](https://github.com/user-attachments/assets/5af91336-b5ab-4438-bea2-566baffd6a38)

# Task: Fix "View Club" Button and Implement Dynamic Routing

## Problem:
- The "View Club" button is not working, preventing users from viewing the full information of the club.

## Goal:
- Implement dynamic routing to fetch and display all relevant information about a club when a user clicks the "View Club" button.

## Steps to Resolve:

1. **Check Button Functionality:**
   - Ensure that the button triggers an event when clicked.
   - Verify that the button is correctly linked to a route.

2. **Create Dynamic Route:**
   - Set up dynamic routing (e.g., `/clubs/[clubId]`) in your application to fetch and display club details based on the `clubId`.

3. **Fetch Club Data:**
   - On the dynamic route, fetch the club details from the backend or API using the `clubId`.
   - Ensure the necessary club information (type, start date, description, etc.) is rendered on the page.

4. **Test Functionality:**
   - Verify that clicking the "View Club" button on any card correctly navigates to the dynamic route.
   - Ensure that all relevant club details are displayed for the user.

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/86941244/375938819-5af91336-b5ab-4438-bea2-566baffd6a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkwNzcsIm5iZiI6MTcyODcyODc3NywicGF0aCI6Ii84Njk0MTI0NC8zNzU5Mzg4MTktNWFmOTEzMzYtYjVhYi00NDM4LWJlYTItNTY2YmFmZmQ2YTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNDU3MDEzMTcyZTU2ZTUzMzcxYTU5NDFlMWVlZmZkZjQ1MjNjN2UzZGY2N2FkZGE4OWMxMzhiMThkNGIzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.arG8mcCXjG6E-4d83mNF7Sw_CX82m0yPMEZM_Cv-Qpo)
> 
> # Task: Fix "View Club" Button and Implement Dynamic Routing
> ## Problem:
> * The "View Club" button is not working, preventing users from viewing the full information of the club.
> 
> ## Goal:
> * Implement dynamic routing to fetch and display all relevant information about a club when a user clicks the "View Club" button.
> 
> ## Steps to Resolve:
> 1. **Check Button Functionality:**
>    
>    * Ensure that the button triggers an event when clicked.
>    * Verify that the button is correctly linked to a route.
> 2. **Create Dynamic Route:**
>    
>    * Set up dynamic routing (e.g., `/clubs/[clubId]`) in your application to fetch and display club details based on the `clubId`.
> 3. **Fetch Club Data:**
>    
>    * On the dynamic route, fetch the club details from the backend or API using the `clubId`.
>    * Ensure the necessary club information (type, start date, description, etc.) is rendered on the page.
> 4. **Test Functionality:**
>    
>    * Verify that clicking the "View Club" button on any card correctly navigates to the dynamic route.
>    * Ensure that all relevant club details are displayed for the user.

Great ,go ahead.
the level of this issue depends on your work
