### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by ShreyaSnehal** [Yash-Ainapure/dypcetclubs.live#58]
The color of the titles in the nav bar should change as it is not visible while scrolling due to the white background.
![image](https://github.com/user-attachments/assets/8b4c6b61-5e31-4779-b9da-fbac904ac191)

**Comment by Yash-Ainapure** [comment]
> The color of the titles in the nav bar should change as it is not visible while scrolling due to the white background. ![image](https://private-user-images.githubusercontent.com/140809459/375256432-8b4c6b61-5e31-4779-b9da-fbac904ac191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjQ1NTMsIm5iZiI6MTcyODU2NDI1MywicGF0aCI6Ii8xNDA4MDk0NTkvMzc1MjU2NDMyLThiNGM2YjYxLTVlMzEtNDc3OS1iOWRhLWZiYWM5MDRhYzE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMjQ0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzM0ZThkNDA0NmZlYjdkZjUxMmVlMDY3YzhiYzI2ZGViM2I5ZjBmYjcyYmRjNzgzMDhhMDc0NDk0MGY5OTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2RdD9zqjTIpflCYsiQv-5njpFcp4tFscT2AHY_GRAvM)

Could you explain how would you fix this?
