### ISSUE TITLE
add Footer same as home page designs 

### ISSUE THREAD

**Issue by devxMani** [Yash-Ainapure/dypcetclubs.live#6]
![image](https://github.com/user-attachments/assets/6bed5e74-c1f4-45c3-86b9-c68175afe384)
add GSOC ext and hacktoberfest label to this feature 
Feel free to provide any input, and I will proceed accordingly."

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/122438942/373651268-6bed5e74-c1f4-45c3-86b9-c68175afe384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDgzNjksIm5iZiI6MTcyODA0ODA2OSwicGF0aCI6Ii8xMjI0Mzg5NDIvMzczNjUxMjY4LTZiZWQ1ZTc0LWMxZjQtNDVjMy04NmI5LWM2ODE3NWFmZTM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxMzIxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWQ0ZjM5ZDE2MDU0MGFiZDE3OTBmMDEzOGE4YzFkZTQyNzEzNDhkYTcyMjk5MjNjYzUxZDU3ZTdmZGI4OTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p1jPjQuL9B7LC0S9XGfGqSPeyTwNllwkju67RUS1lqA) add GSOC ext and hacktoberfest label to this feature Feel free to provide any input, and I will proceed accordingly."

you can work on it

**Comment by harsh0853** [comment]
Hey! Can you please assign this to me ?

**Comment by Yash-Ainapure** [comment]
> Hey! Can you please assign this to me ?

@devxMani , are you working on it?

**Comment by devxMani** [comment]
@Yash-Ainapure i am working on it i'll do it by tomorrow i am little busy because of my placements I'll do it tomorrow surely...

**Comment by itznayan** [comment]
can i work on this issue ?
