### ISSUE TITLE
Add Anchor link to logo and site Name

### ISSUE THREAD

**Issue by vedhcet-07** [Yash-Ainapure/dypcetclubs.live#60]
Sir it is important that whenever we click on logo or brand name , we are redireted to home page . 

I observed that this is missing in the site . 

If you assign this to me under gssoc and hacktober fest , i will do this asap . I know its a simple task sir , but this to matters 

Waiting for your response .

Thank you

**Comment by Yash-Ainapure** [comment]
> Sir it is important that whenever we click on logo or brand name , we are redireted to home page .
> 
> I observed that this is missing in the site .
> 
> If you assign this to me under gssoc and hacktober fest , i will do this asap . I know its a simple task sir , but this to matters
> 
> Waiting for your response .
> 
> Thank you

Sure

**Comment by vikas83pal** [comment]
@Yash-Ainapure please assign me this issue as it is hacktoberfest and gssoc-ext
