### ISSUE TITLE
Navbar Visibility and Home Button Not Functioning Properly

### ISSUE THREAD

**Issue by Priyanshu282003** [Yash-Ainapure/dypcetclubs.live#63]
Description: The following issues have been identified with the website's navigation bar:

Navbar Text Visibility on White Background: When scrolling to sections with a white background, the navbar text becomes invisible, making it difficult for users to navigate. This is likely a problem with the color contrast between the text and the background.

Home Button Not Functioning: Clicking the "Home" button on the navbar does not redirect the user to the homepage as expected. The button appears non-responsive.

Steps to Reproduce:

Scroll to a section of the page that has a white or light background.
Observe the navbar text becoming invisible.
Click on the "Home" button and notice that it does not redirect to the homepage.
Expected Behavior:

The navbar text should maintain visibility across all sections, regardless of the background color (use contrasting colors or a background for the navbar).
The "Home" button should be functional and direct users to the homepage when clicked.
Possible Solution:

Adjust the CSS to ensure that navbar text changes color based on the background it overlays, or add a background color to the navbar itself.
Fix the functionality of the "Home" button by ensuring the correct link or redirect is in place.
Screenshot:
![image](https://github.com/user-attachments/assets/1173f0ef-0788-4e00-b9c3-364fe2419654)

**Comment by Yash-Ainapure** [comment]
> Description: The following issues have been identified with the website's navigation bar:
> 
> Navbar Text Visibility on White Background: When scrolling to sections with a white background, the navbar text becomes invisible, making it difficult for users to navigate. This is likely a problem with the color contrast between the text and the background.
> 
> Home Button Not Functioning: Clicking the "Home" button on the navbar does not redirect the user to the homepage as expected. The button appears non-responsive.
> 
> Steps to Reproduce:
> 
> Scroll to a section of the page that has a white or light background. Observe the navbar text becoming invisible. Click on the "Home" button and notice that it does not redirect to the homepage. Expected Behavior:
> 
> The navbar text should maintain visibility across all sections, regardless of the background color (use contrasting colors or a background for the navbar). The "Home" button should be functional and direct users to the homepage when clicked. Possible Solution:
> 
> Adjust the CSS to ensure that navbar text changes color based on the background it overlays, or add a background color to the navbar itself. Fix the functionality of the "Home" button by ensuring the correct link or redirect is in place. Screenshot: ![image](https://private-user-images.githubusercontent.com/128988712/375397321-1173f0ef-0788-4e00-b9c3-364fe2419654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjgyNTgsIm5iZiI6MTcyODU2Nzk1OCwicGF0aCI6Ii8xMjg5ODg3MTIvMzc1Mzk3MzIxLTExNzNmMGVmLTA3ODgtNGUwMC1iOWMzLTM2NGZlMjQxOTY1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMzQ1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODM1N2ZlNjg1MDM0YWQyMTQ4MjFkMDdiMjI0OThmMmQ1OTEzNzIxMjIzYTYwNGE3ZDZlZmVmYjRlYzE1NGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jl2jU-1J-RaXs9RvlmZZZ9Ml8paozs46P26kb2exCtA)

Explain,how you are going to fix the navbar issue
