### ISSUE TITLE
Fixing UI of registration form

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#65]
Hello I would like to fix the UI of register form when error messages are displayed
the title is hidden to some extent

![image](https://github.com/user-attachments/assets/c3f2a218-c08d-4134-ad33-4e7037769475)

Pls assign this to me

**Comment by Yash-Ainapure** [comment]
> Hello I would like to fix the UI of register form when error messages are displayed the title is hidden to some extent
> 
> ![image](https://private-user-images.githubusercontent.com/114927759/375431129-c3f2a218-c08d-4134-ad33-4e7037769475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDgxMTEsIm5iZiI6MTcyODY0NzgxMSwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc1NDMxMTI5LWMzZjJhMjE4LWMwOGQtNDEzNC1hZDMzLTRlNzAzNzc2OTQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMTU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGI0Y2Y3M2U4MzYyMTRmNzlkMjdlZmI3YjgyNWMyN2UyY2FjOTg0MDQ3NWJiY2NiMDI0ZGNiMDZiZjc4OGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWQpF5GrG39vaOZJjYQC4ZCBos2aIbFLEZPvNopOy2s)
> 
> Pls assign this to me

At my side the titla is not getting hidden,which device it is?

**Comment by Gauravtb2253** [comment]
> > Hello I would like to fix the UI of register form when error messages are displayed the title is hidden to some extent
> > ![image](https://private-user-images.githubusercontent.com/114927759/375431129-c3f2a218-c08d-4134-ad33-4e7037769475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDgxMTEsIm5iZiI6MTcyODY0NzgxMSwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc1NDMxMTI5LWMzZjJhMjE4LWMwOGQtNDEzNC1hZDMzLTRlNzAzNzc2OTQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMTU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGI0Y2Y3M2U4MzYyMTRmNzlkMjdlZmI3YjgyNWMyN2UyY2FjOTg0MDQ3NWJiY2NiMDI0ZGNiMDZiZjc4OGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWQpF5GrG39vaOZJjYQC4ZCBos2aIbFLEZPvNopOy2s)
> > Pls assign this to me
> 
> At my side the titla is not getting hidden,which device it is?

When the error message of validation is displayed the title is getting hidden

**Comment by Yash-Ainapure** [comment]
> > > Hello I would like to fix the UI of register form when error messages are displayed the title is hidden to some extent
> > > ![image](https://private-user-images.githubusercontent.com/114927759/375431129-c3f2a218-c08d-4134-ad33-4e7037769475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDgxMTEsIm5iZiI6MTcyODY0NzgxMSwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc1NDMxMTI5LWMzZjJhMjE4LWMwOGQtNDEzNC1hZDMzLTRlNzAzNzc2OTQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMTU2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGI0Y2Y3M2U4MzYyMTRmNzlkMjdlZmI3YjgyNWMyN2UyY2FjOTg0MDQ3NWJiY2NiMDI0ZGNiMDZiZjc4OGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWQpF5GrG39vaOZJjYQC4ZCBos2aIbFLEZPvNopOy2s)
> > > Pls assign this to me
> > 
> > 
> > At my side the titla is not getting hidden,which device it is?
> 
> When the error message of validation is displayed the title is getting hidden

Didn't know how it's getting hidden to you.but at my device its visible
let it be,try to contribute to some different issues.
