### ISSUE TITLE
Home and clubs button not working

### ISSUE THREAD

**Issue by 2ushar03** [Yash-Ainapure/dypcetclubs.live#69]
Sir, it is important that when a user clicks on the Home button or Clubs button, it should work and perform its intended functionality.

This feature is useful as it enhances user navigation and is necessary for SEO optimization of the website. It is a must-have for a better user experience.

I have seen this feature implemented in many other projects, as it is a standard practice in web development.

As I am new here (first-time contributor), I would like to try implementing this feature.

please assign me this issue and also add the Hacktoberfest and GSSOC-ext labels.

Thank you!

**Comment by vikas83pal** [comment]
@Yash-Ainapure please assign me this issue 


Thank you!

**Comment by Yash-Ainapure** [comment]
> Sir, it is important that when a user clicks on the Home button or Clubs button, it should work and perform its intended functionality.
> 
> This feature is useful as it enhances user navigation and is necessary for SEO optimization of the website. It is a must-have for a better user experience.
> 
> I have seen this feature implemented in many other projects, as it is a standard practice in web development.
> 
> As I am new here (first-time contributor), I would like to try implementing this feature.
> 
> please assign me this issue and also add the Hacktoberfest and GSSOC-ext labels.
> 
> Thank you!

How would you implement it,
i wanted it to hide the home page and get redirected to a clubs/events page where we get proper all clubs/events listed there and also a small search bar to search there, could you do that.
the level of this issue could depend on the work you do
