### ISSUE TITLE
[Bug]: navigation issue

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [Yash-Ainapure/dypcetclubs.live#79]
![image](https://github.com/user-attachments/assets/9b347e7a-56e8-433d-a825-7e2f113e20f6)
here not showing the issue in the navbar , not showing the text color and mixed with the bg color

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/86941244/375940037-9b347e7a-56e8-433d-a825-7e2f113e20f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkyOTksIm5iZiI6MTcyODcyODk5OSwicGF0aCI6Ii84Njk0MTI0NC8zNzU5NDAwMzctOWIzNDdlN2EtNTZlOC00MzNkLWE4MjUtN2UyZjExM2UyMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwMjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzY2ZmMDAwMGQ3ZDcyNWVkNTYzZmU1YmM0NTY3ZTc2OWU5N2NiYWUwNDYwNDgzNmRiNWFlOWFhN2EwODEzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMBGtSMYItYyx8YQECmD5MCJlffwniEuk2o2vSdxeSk) here not showing the issue in the navbar , not showing the text color and mixed with the bg color

Sure, go ahead
