### ISSUE TITLE
Responsive Landing Page and Navbar

### ISSUE THREAD

**Issue by jainaryan04** [Yash-Ainapure/dypcetclubs.live#8]
Home page is not optimised for mobile view. Please assign this issue to me so I can work on making it responsive across screen sizes.
Also, please add hacktoberfest and gssoc labels.

![image](https://github.com/user-attachments/assets/1afe1375-ff66-4cf9-ae9b-b379ae2da425)

**Comment by Yash-Ainapure** [comment]
Sure Home page is not optimised for mobile view. Please assign this issue to me so I can work on making it responsive across screen sizes. Also, please add hacktoberfest and gssoc labels.
> 
> ![image](https://private-user-images.githubusercontent.com/138214350/373800302-1afe1375-ff66-4cf9-ae9b-b379ae2da425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTY2OTIsIm5iZiI6MTcyODA5NjM5MiwicGF0aCI6Ii8xMzgyMTQzNTAvMzczODAwMzAyLTFhZmUxMzc1LWZmNjYtNGNmOS1hZTliLWIzNzlhZTJkYTQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTlkOThkNTQ5N2NlZjk2ZjVlZjM4MzFkMWU0YTcyMGRlNWYzMmE4YjcxNTgxMzY2MzEyZWVhN2NlNTJkNTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eAIodf-3qQWiJvIDpX8t1p1ro1aYG0PzKDVHHeA8Vkw)
Sure, go ahead
