### ISSUE TITLE
Nav link not woking 

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [Yash-Ainapure/dypcetclubs.live#80]

**Comment by Yash-Ainapure** [comment]
> _No description provided._

could you explain some more details about what things you will do?
anyway, you could do it later,first finish the previous assigned tasks,then we could do this

**Comment by Dhruv-pahuja** [comment]
![image](https://github.com/user-attachments/assets/0deb96e8-093f-4941-8d8b-29392c3bcc9a)
here , the Nav links are not working except about link, when we click on it nothing happens when user is on home page and when user is on about page a white blank page opens when we click on any nav link 


So can you please assign this issue to me, so that i can work on it and solve this quickly .... @Yash-Ainapure 
and aslo please add label1 tag to this issue please

**Comment by Ameerjafar** [comment]
@Yash-Ainapure can you assign me this issue

**Comment by Yash-Ainapure** [comment]
> ![image](https://private-user-images.githubusercontent.com/100836518/375961456-0deb96e8-093f-4941-8d8b-29392c3bcc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc5OTIsIm5iZiI6MTcyODc5NzY5MiwicGF0aCI6Ii8xMDA4MzY1MTgvMzc1OTYxNDU2LTBkZWI5NmU4LTA5M2YtNDk0MS04ZDhiLTI5MzkyYzNiY2M5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTczMWYyNzlhNDVkMTdiZjE1ZmViNjgwY2FjMGQzOGU0NWVmOTFjYzdiNGJmOTc0MTg5YjEwZThmYjg4MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qC93ZC-D48536W70x6l8wJb8W3eE4zgFawjJ0k6IIKQ) here , the Nav links are not working except about link, when we click on it nothing happens when user is on home page and when user is on about page a white blank page opens when we click on any nav link
> 
> So can you please assign this issue to me, so that i can work on it and solve this quickly .... @Yash-Ainapure and aslo please add label1 tag to this issue.

Ok,
just make sure to make it look good,
when we click on a navbar button,the home page should get hidden and that specific page should get visible  with the navbar still present visible on top

**Comment by Dhruv-pahuja** [comment]
> > ![image](https://private-user-images.githubusercontent.com/100836518/375961456-0deb96e8-093f-4941-8d8b-29392c3bcc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc5OTIsIm5iZiI6MTcyODc5NzY5MiwicGF0aCI6Ii8xMDA4MzY1MTgvMzc1OTYxNDU2LTBkZWI5NmU4LTA5M2YtNDk0MS04ZDhiLTI5MzkyYzNiY2M5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTczMWYyNzlhNDVkMTdiZjE1ZmViNjgwY2FjMGQzOGU0NWVmOTFjYzdiNGJmOTc0MTg5YjEwZThmYjg4MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qC93ZC-D48536W70x6l8wJb8W3eE4zgFawjJ0k6IIKQ) here , the Nav links are not working except about link, when we click on it nothing happens when user is on home page and when user is on about page a white blank page opens when we click on any nav link
> > So can you please assign this issue to me, so that i can work on it and solve this quickly .... @Yash-Ainapure and aslo please add label1 tag to this issue.
> 
> Ok, just make sure to make it look good, when we click on a navbar button,the home page should get hidden and that specific page should get visible with the navbar still present visible on top

bro @Yash-Ainapure I asked it to assigned to me not KuldeepSingh

**Comment by Yash-Ainapure** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/100836518/375961456-0deb96e8-093f-4941-8d8b-29392c3bcc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc5OTIsIm5iZiI6MTcyODc5NzY5MiwicGF0aCI6Ii8xMDA4MzY1MTgvMzc1OTYxNDU2LTBkZWI5NmU4LTA5M2YtNDk0MS04ZDhiLTI5MzkyYzNiY2M5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTM0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTczMWYyNzlhNDVkMTdiZjE1ZmViNjgwY2FjMGQzOGU0NWVmOTFjYzdiNGJmOTc0MTg5YjEwZThmYjg4MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qC93ZC-D48536W70x6l8wJb8W3eE4zgFawjJ0k6IIKQ) here , the Nav links are not working except about link, when we click on it nothing happens when user is on home page and when user is on about page a white blank page opens when we click on any nav link
> > > So can you please assign this issue to me, so that i can work on it and solve this quickly .... @Yash-Ainapure and aslo please add label1 tag to this issue.
> > 
> > 
> > Ok, just make sure to make it look good, when we click on a navbar button,the home page should get hidden and that specific page should get visible with the navbar still present visible on top
> 
> bro @Yash-Ainapure I asked it to assigned to me not KuldeepSingh

Sorry for my mistake,
you can work now
