### ISSUE TITLE
On mobile hamburger menu is colliding with login button and menu is need not to be sticky. 

### ISSUE THREAD

**Issue by varma-101** [Yash-Ainapure/dypcetclubs.live#82]
![Screenshot_2024-10-12-19-26-15-979_com android chrome](https://github.com/user-attachments/assets/73627598-12da-4344-82fb-3626915fc000)
See on right top of the screen shot.

**Comment by Yash-Ainapure** [comment]
> ![Screenshot_2024-10-12-19-26-15-979_com android chrome](https://private-user-images.githubusercontent.com/138625491/375962720-73627598-12da-4344-82fb-3626915fc000.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc4MzEsIm5iZiI6MTcyODc5NzUzMSwicGF0aCI6Ii8xMzg2MjU0OTEvMzc1OTYyNzIwLTczNjI3NTk4LTEyZGEtNDM0NC04MmZiLTM2MjY5MTVmYzAwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjI5OWIyOGZkMzExNTMzYTkyNGY1ZThlNzRhMjNlZGQzMDAxZmQwZDI0MjUwZTNiOWJmMmMxZTBkMzljZTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gq-EbQOmMnxJ42FFCz3mDBBsi8GggX6iNV6X_pM6tMc) See on right top of the screen shot.

Just hide the menu for mobile responsiveness

**Comment by varma-101** [comment]
> > ![Screenshot_2024-10-12-19-26-15-979_com android chrome](https://private-user-images.githubusercontent.com/138625491/375962720-73627598-12da-4344-82fb-3626915fc000.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc4MzEsIm5iZiI6MTcyODc5NzUzMSwicGF0aCI6Ii8xMzg2MjU0OTEvMzc1OTYyNzIwLTczNjI3NTk4LTEyZGEtNDM0NC04MmZiLTM2MjY5MTVmYzAwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjI5OWIyOGZkMzExNTMzYTkyNGY1ZThlNzRhMjNlZGQzMDAxZmQwZDI0MjUwZTNiOWJmMmMxZTBkMzljZTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gq-EbQOmMnxJ42FFCz3mDBBsi8GggX6iNV6X_pM6tMc) See on right top of the screen shot.
> 
> Just hide the menu for mobile responsiveness

But then how users can access menu items.?

**Comment by Yash-Ainapure** [comment]
> > > ![Screenshot_2024-10-12-19-26-15-979_com android chrome](https://private-user-images.githubusercontent.com/138625491/375962720-73627598-12da-4344-82fb-3626915fc000.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTc4MzEsIm5iZiI6MTcyODc5NzUzMSwicGF0aCI6Ii8xMzg2MjU0OTEvMzc1OTYyNzIwLTczNjI3NTk4LTEyZGEtNDM0NC04MmZiLTM2MjY5MTVmYzAwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNTMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjI5OWIyOGZkMzExNTMzYTkyNGY1ZThlNzRhMjNlZGQzMDAxZmQwZDI0MjUwZTNiOWJmMmMxZTBkMzljZTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gq-EbQOmMnxJ42FFCz3mDBBsi8GggX6iNV6X_pM6tMc) See on right top of the screen shot.
> > 
> > 
> > Just hide the menu for mobile responsiveness
> 
> But then how users can access menu items.?

Adding both login button and ham burger is not good for UX,
do you have any idea how we can fix that?
Or make the hamburger visible and hide the club login button(as this is just for club admins only which we suitable for desktop only)

**Comment by varma-101** [comment]
ok then i'll keep login btn inside the hamburger menu.

**Comment by varma-101** [comment]
i've completed the task and made a pr please add level labels to it and merge it.pr has no conflicts with the main branch.
