### ISSUE TITLE
[UI ENHANCEMENT] : Adding GSAP Animations to langing page | gssoc-ext | level 3

### ISSUE THREAD

**Issue by Hamza1821** [Yash-Ainapure/dypcetclubs.live#83]
### **i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations**

please asign this to me under  gssoc-ext level 3

**Comment by Yash-Ainapure** [comment]
> ### **i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations**
> please asign this to me under gssoc-ext level 3

The website needs to be light ,we currently don't need any high animations now
