### ISSUE TITLE
Add Cursor Effect 

### ISSUE THREAD

**Issue by KrishChothani** [Yash-Ainapure/dypcetclubs.live#84]
Add Cursor effect with trail and glow effect

![image](https://github.com/user-attachments/assets/52388d24-fb55-45d6-bd9d-cf78fd196e57)

**Comment by Yash-Ainapure** [comment]
> Add Cursor effect with trail and glow effect
> 
> ![image](https://private-user-images.githubusercontent.com/143370415/376020114-52388d24-fb55-45d6-bd9d-cf78fd196e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDIwNzQsIm5iZiI6MTcyODg0MTc3NCwicGF0aCI6Ii8xNDMzNzA0MTUvMzc2MDIwMTE0LTUyMzg4ZDI0LWZiNTUtNDVkNi1iZDlkLWNmNzhmZDE5NmU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNzQ5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjlhNGZkZjY1MjE2MzA1ZjE3ZWY0OThjMmYxMmFjNzYxODEzZWY4OWU2OWFiZGM3OGRlYTIwZDJjYzIzZWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X2rySIZdAB4O9gWrFw7xCBpZ8JpHKorPup3Tuh_LCwI)

Sorry but ,we want to keep this website light and minimilistic as possible and adding such animations is not good at present.
