### ISSUE TITLE
Adding hover effects on upcoming events

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#87]
Hello
I would like to add hover effects on the upcoming event cards
When we hover on the card the background will become transparent and only the text will be shown
This will look nice
Pls assign this to me

**Comment by Yash-Ainapure** [comment]
> Hello I would like to add hover effects on the upcoming event cards When we hover on the card the background will become transparent and only the text will be shown This will look nice Pls assign this to me

Sorry Gaurav,but we want to keep the UI simple and minimilistic ,at present we don't require such animations.
try contributing to other issues
