### ISSUE TITLE
Add Google Authentication with Handling for Additional Fields

### ISSUE THREAD

**Issue by Laxmi01345** [Yash-Ainapure/dypcetclubs.live#88]
Description:
Add Google Authentication to the current registration form. After successful sign-in, pre-fill the Email field with the user's Google account information. Ensure users can still fill in additional fields (Club Name, Description, Password, File Upload) and submit the form.

Expected Behavior:

1. The "Register with Google" button initiates the Google OAuth flow.
2. After sign-in, the form’s Email field is pre-filled.
3. The user completes the remaining fields and submits the form.

Current Behavior:

1. No Google Authentication.
2. All fields must be manually filled.

I want to work on this issue. Please assign it to me under GSSoC-Ext and Hacktoberfest.

**Comment by Yash-Ainapure** [comment]
> Description: Add Google Authentication to the current registration form. After successful sign-in, pre-fill the Email field with the user's Google account information. Ensure users can still fill in additional fields (Club Name, Description, Password, File Upload) and submit the form.
> 
> Expected Behavior:
> 
> 1. The "Register with Google" button initiates the Google OAuth flow.
> 2. After sign-in, the form’s Email field is pre-filled.
> 3. The user completes the remaining fields and submits the form.
> 
> Current Behavior:
> 
> 1. No Google Authentication.
> 2. All fields must be manually filled.
> 
> I want to work on this issue. Please assign it to me under GSSoC-Ext and Hacktoberfest.

As per the website flow,we need a super admin approving system for the club admin before registering,
so currently we cannot add google auth here,try to contribute to other issues,thanks.
