### ISSUE TITLE
Register page not visible

### ISSUE THREAD

**Issue by Gauravtb2253** [Yash-Ainapure/dypcetclubs.live#99]
The register form is not visible when we click it
I can solve this issue

![image](https://github.com/user-attachments/assets/33f42af7-8022-430b-8475-ed4a09d2ec11)

**Comment by Yash-Ainapure** [comment]
> The register form is not visible when we click it I can solve this issue
> 
> ![image](https://private-user-images.githubusercontent.com/114927759/376616024-33f42af7-8022-430b-8475-ed4a09d2ec11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTczODAsIm5iZiI6MTcyODk5NzA4MCwicGF0aCI6Ii8xMTQ5Mjc3NTkvMzc2NjE2MDI0LTMzZjQyYWY3LTgwMjItNDMwYi04NDc1LWVkNGEwOWQyZWMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMjU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWZjZmE5NTY1MzY5NWJlNjAzNTE3Njk1M2M2ZDZlMDdkN2M0NDk3YmRkMGEyZjc4ZGRjYjJiMGU1OWRiM2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3dYHmd27R5bMlhm8_UziXNkRWHupZA3LITZ7i3Zfe9g)

Which register are you talking about,the events or login register button?
